### ISSUE TITLE
Can't install webui7

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#1]
When I try to install linuxmuster-webui7 in the latest lmn v7 appliance I get this error (middle of the picture):

![lmnv7 auslieferungszustand wird ausgefuhrt - oracle vm virtualbox_053](https://user-images.githubusercontent.com/708888/39580845-4fa2b4c0-4f14-11e8-8861-e5f40356eed3.png)

**Comment by netzint** [comment]
This is a known Bug in the pre Alpha version. This will be fixed in the alpha release. At the moment it is enough to run "apt-get install linuxmuster-webui7" again.

**Comment by netzint** [comment]
Should be fixed in the Alpha version "linuxmuster-webui7_1.0.10-1".
