### ISSUE TITLE
Can't login with a teacher account

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#10]
I can't login with a teacher account. Are logins enabled for teachers? 

Login is possible with `root`.

**Comment by PLanB2008** [comment]
Login as teacher should be possible. Please check /etc/ajenti/config.yml for linuxmuster  ldap credentials. 

Section should contain the ldap credentials:

linuxmuster:
  ldap:
    binddn: CN=global-binduser,OU=Management,OU=GLOBAL,DC=linuxmuster,DC=lan
    bindpw: PASSWORD
    host: server
    searchdn: DC=linuxmuster,DC=lan

Please check and report. It might happen that the installation process did not enter all values correct.

**Comment by zefanja** [comment]
Seems to work with the latest version. Or maybe I've installed the webui after running `linuxmuster-setup`
