### ISSUE TITLE
Drag&Drop upload for session

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#101]
Hello @PLanB2008,

Thank you for your work about it.
I have some questions : 

1) When a file is uploaded, it comes in `'/srv/samba/schools/'+school+'/'+role+'/'+username+'/transfer/'` --> perfect, but the owner/group is root/root, I would suggest to make a chown after the upload to correct this. Handle this with a generic path like /srv/upload could be tricky : it can occur a conflict when 2 teachers use this at the same time. Ok ?

2) I tried to use `sophomorix-transfer` to copy some files : 

```sophomorix-transfer -jj --scopy --from-user de --to-user frayka --from-path transfer/testfile.txt --to-path transfer/```

Problem : the destination files do not have the right owner : 

```
$ ls -la /srv/samba/school/default-school/students/10a/frayka/transfer 
total 40
drwxrwx---+ 2       3000004 users  4096 mai   22 17:03 .
drwxrwx---+ 3 DOM\frayka users  4096 mai   20 22:29 ..
-rwxrwx---+ 1       3000000 users     0 mai   22 17:03 testfile.txt```

How is it on your server ?

3) Later : handle multiple files upload and case when uploaded file have the same name as an existing file.

**Comment by PLanB2008** [comment]
Hi @kiarn ,

this is an issue I ran into as well and still has to be fixed..

First the idea was to share  data directly wen using the drag & drop field with the chosen user or session. But when I saw your code I thought maybe it would make more sense to upload the file in the transfer folder first and share it from there. This works right now but lacks the necessary user permissions.

I tried to overwrite the permissions  as well by doing something like:
`sophomorix-transfer -jj --scopy --from-user de --to-user frayka --from-path transfer/testfile.txt --to-path transfer/`
Maybe @jeffbeck could add a command to set the permissions on overwrite? Or another command to set the permissions correctlry?


Another  workaround could be:

1. upload file in generic folder (eg. /srv/temp/) 
2. Move the file in the home folder of the teacher by using:
`sophomorix-transfer --from-unix-path /srv/upload/... --to-user <user1>,<user2>-exam, ... --subdir <dir>`
3. Delete the temporary file from /srv/upload/

**Comment by kiarn** [comment]
> First the idea was to share data directly wen using the drag & drop field with the chosen user or session. But when I saw your code I thought maybe it would make more sense to upload the file in the transfer folder first and share it from there. This works right now but lacks the necessary user permissions.

I think we can build a little api to change permissions, it's not that difficult.

**Comment by kiarn** [comment]
Chown done.

**Comment by kiarn** [comment]
> 3) Later : case when uploaded file have the same name as an existing file.

In this case, the uploaded file will overwrite the existing file, I think we can let it so ...

**Comment by PLanB2008** [comment]
This seems to work flawlessly for now. I'll close the issue

**Comment by PLanB2008** [comment]
We have to reopen this issue. This only works in a single server environment.

If the fileserver is conncted via DFS (which is used in multischool environments) we cannot upload directly to the transfer folder of the user.

We have to upload to a generic folder on the LMN server (eg. /srv/upload/) and trigger sophomorix to move this file (sophomorix reads the DFS configuration and uses samba to transfer the file to the correct server)

I gonne implement this using 
    sophomorix-transfer --from-unix-path /srv/upload/... --to-user <user1>,<user2>-exam, ... --subdir <dir>

I think this will also work for the user permissions...

**Comment by kiarn** [comment]
Sorry to ask a dummy question : what's DFS ?

**Comment by PLanB2008** [comment]
DFS stands for distributed filesystem which is a samba feature. This allows the clients to have a transparent way to call our data without knowing on which server they are located. The access is handelt  by samba, so samba knows which (sub)directory is located on which server.
For us this means we cannot be sure the fileserver is always reachable on unix filesystem.
In our concept this should only effects the school drives, eg: 

/srv/samba/default-school
/srv/samba/berlin-middleschool

**Comment by PLanB2008** [comment]
Should be fixed
