### ISSUE TITLE
teachers can change other teachers passwords

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#104]
If I create a teacher and login with it, I can access the site `view/lm/users/teachers`. There a teacher can change other teachers passwords.

**Comment by kiarn** [comment]
Hello @zefanja,

Thanks, corrected here : https://github.com/linuxmuster/linuxmuster-webui7/commit/2af76aaffe8b37857a6c0aeb1a9510bae7bb7ee2

@PLanB2008 : I think we should split `lm:users:passwords` into `lm:users:teacher-password` and `lm:users:student-password` to get more flexibility and simply avoid these cases. What do you think ?

**Comment by PLanB2008** [comment]
@kiarn : Yes I think this would help a lot. Maybe we should also extend this to admins and global admins

**Comment by PLanB2008** [comment]
This seems to be fixed now? @zefanja can you confirm?

**Comment by zefanja** [comment]
@PLanB2008 Yes, fixed.
