### ISSUE TITLE
collected located in Folder transfer

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-webui7#105]
Hi everyone,

i noticed that, when a teacher collects Things from students it is stored in Home_auf_Server/transfer/collected
I understand the wish to keep the Home of a teacher tidy, but placing "collected" inside transfer is risky.
If a teacher, who has collected befor, is sharing Files with a class, he will see in the sharing box the collected Folder: one wring tick, an he will share everything he has ever collected with another session.
I think it would be very advisable to move the collected Folder one Folder down an thus outside transfer.
Home would have these Folders:
"Einstellungen"
"transfer"
"collected"

Yours

Holger

**Comment by PLanB2008** [comment]
I'd rather prefer preventing the user from choosing collected directly than clutter the home directory.

**Comment by baumhof** [comment]
Hi Till,
thanks for your fast response :-)
We diskussed that posibility at the  Meeting too: making the collected Folder "unklickable" in WebUI.
The concensus was to rather move it one Folder down, even if this means cluttering the home.
We know our Collegues: one will always find a way to still share that folder (rename it first for example).
Thats why we think moving is a better solution. We know thats only a little more way to go for the collegues to fail: bat that might just be the inch thats needed. 

Or how about that: adding a folder to transfer named "share" which holds the "to be shared" files.
collected would then lie beside "share" not in it.

Yours 
Holger

**Comment by kiarn** [comment]
As a developer, I would follow the idea of @PLanB2008 to keep a logical structur.
As a teacher, my experience knows that @baumhof is fully right.
As a human being, I know that my answer doesn't help anyone.

So, even if it's really not beautiful, I would try to prevent as much as possible error in the practice and eventually let both directory as "brothers" instead of "father/son", I think it's easier for the teachers.

**Comment by kiarn** [comment]
Hi @baumhof 

As you said, our colleagues will always find a way to share a folder, even if its location is one folder up. So I choose to solve it with the simple way: the collected folder is now hidden in the share modal. This will prevent the most common problems.

Arnaud
