### ISSUE TITLE
Management of Projects

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-webui7#106]
I have found no way to assign another Projectadmin other than the teacher creating the Project.
Not even global-admin has the capability to assign another Projectadmin.

Not a big Flaw: more like a Featurerequest :-)

Yours 

Holger

**Comment by PLanB2008** [comment]
This is something @kiarn is currently working on.

**Comment by baumhof** [comment]
Lightningspeed
Thumbs up
Thank you Arnaud.
I will test it.
