### ISSUE TITLE
text error in command help for linuxmuster-setup -h

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-webui7#109]
Long Parameter for state is falsely listed as "country" in command help:

![Bildschirmfoto 2019-07-24 um 09 14 09](https://user-images.githubusercontent.com/48863382/61772793-671b2080-adf3-11e9-951b-b78bc8cae08e.png)

**Comment by kiarn** [comment]
Hello @RolandBBerlin 

It's not related to the WebUI, I made a little ticket in linuxmuster-base7 : https://github.com/linuxmuster/linuxmuster-base7/issues/74

**Comment by kiarn** [comment]
Fixed : https://github.com/linuxmuster/linuxmuster-base7/commit/0c7c4e1d06e0ca42b77e8a123f55927e1655f2c0
