### ISSUE TITLE
Error on sophomorix-check when setting encoding in WebUI

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-webui7#111]
I have set encoding to "UTF-8" in WebUI. After adding the first teacher sophomorix-check gives an error:

`#### Encoding results for  teachers.csv                                   ####`
`   * ENCODING:          UTF-8 (configured)`
`   * ENCODING_FORCE:    FALSE`
`   * ENCODING_CHECKED:  UTF8`
`   * Misconfigured ENCODING in configuration file and ENCODING_CHECKED do not match`
`   * Set A) ENCODING_FORCE to "True" if you know better than sophomorix`
`   *  or B) ENCODING to "auto" if you trust sophomorix`

> 

After setting the encoding manually to "UTF8" instead of "UTF-8" in school.conf the error is avoided.

**Comment by kiarn** [comment]
Hello @RolandBBerlin 

I think we need some help from @jeffbeck for this case, because : 

1) UTF8 and UTF-8 are both valid encoding ( see iconv -l )
2) I didn't really understood the role of all the encoding parameter in school.conf ( yes, I need to do my homework, I'm on it ).

**Comment by PLanB2008** [comment]
The optimal way to use this is to keep the encoding in autodetect mode.

Sophomorix should be able to detect your encoding, this best works if you do not add one teacher but several, at best you provide a whole list of teachers and / or students.

WebUI does not force encoding right now, maybe weve to overthink this. 
AFAIK there is no difference between UTF8 and UTF-8. So this could be an sophomorix issue, detecting utf8 without beeing tolerant enough to accept utf-8 as a setting.

@jeffbeck do you have an opinion to about this?

**Comment by jeffbeck** [comment]
The Following is the workflow, that is planned and good:
(Webui does NOT try to detect the encoding. it asumes UTF8)

To add a new students.csv (or teacher.csv, or *.students.csv) BOTH the console administrator AND the webui must do the following:

1) upload new file to server to a temporary location(encoding not known)
2) Register the file with sophomorix-transfer
   This does the following:
  
  Encoding determined:

- copy the file to the correct location under /etc/linusmuster/sophomorix
- create a history of copied files
- convert the file to utf8

Encoding NOT determined
- reject the file if encoding could not be determined
- do nothing under /etc

3) Webui finds only utf8 encoded files

The encoding parameter in school.conf is obsolete. It is there for historical reason.


So do the following:
A) 
set ENCODING back to auto (preferred) or UTF8: sophomorix will know its UTF

B)
If Step 2) fails we have to find out why. Then sophomorix is NOT able to detect the encoding.

To detect the encoding correctly, sophomorix has to find atleast ONE known fistname or lastname in the file with an Umlaut.

So if you live in Munich an think Peter Maßkrug is a good Name for a single user testfile, sophomorix will fail to find out the encoding. (Zwinkersmily at @PLanB2008 )

**Comment by kiarn** [comment]
There wasn't any update for this the past months, and I didn't encounter the same problem.
I think we can close it.
