### ISSUE TITLE
Edit Project members does not show current members

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#112]
When clicking on edit members in projekt group members the current members are highlighted but members don't. So open this dialog and klicking save removes all the members:

![Peek 2019-07-29 19-22](https://user-images.githubusercontent.com/26460239/62068388-31809800-b236-11e9-9130-196bad012fce.gif)

**Comment by kiarn** [comment]
Hello @PLanB2008 

Thanks for your test. I can't reproduce this behaviour with chrome or firefox, it works fine here.
Is sophomorix up to date ?

**Comment by kiarn** [comment]
Maybe the reason : https://github.com/linuxmuster/linuxmuster-webui7/commit/a178e479f7fe9419243e129e23bfb6aea1860581

**Comment by PLanB2008** [comment]
Hello @kiarn 

my bad, I did not update sophomorix to the most current version, so this was my mistake. Now this is working. A minor issue i found:

In the userlist and also the group list in the user properties the top right element lacks the sophomorix-admin-class:
![grafik](https://user-images.githubusercontent.com/26460239/62111432-cf18ad80-b2b0-11e9-9308-1756557d3d21.png)

![grafik](https://user-images.githubusercontent.com/26460239/62111395-ba3c1a00-b2b0-11e9-8efb-51eb06e57b14.png)

**Comment by kiarn** [comment]
The count of the members is also sometime false, I have to check it.

What's the output of : 

`sophomorix-query --group-members --group-full --sam PROJECT -j`
( for the first screenshot )

and 

`sophomorix-query --schoolbase default-school --user-basic --sam USER -j`
( for the second one )
?

**Comment by PLanB2008** [comment]
[first.txt](https://github.com/linuxmuster/linuxmuster-webui7/files/3447236/first.txt)
[second.txt](https://github.com/linuxmuster/linuxmuster-webui7/files/3447237/second.txt)

It always appreas for the top right element.

**Comment by kiarn** [comment]
Ok, that's a CSS problem in Firefox, it's ok in Chrome. I'll have a look later.

**Comment by kiarn** [comment]
It's a bug in Firefox : https://bugzilla.mozilla.org/show_bug.cgi?id=1441048
