### ISSUE TITLE
Import of student.csv list fails

### ISSUE THREAD

**Issue by foer** [linuxmuster/linuxmuster-webui7#114]
After confirming the sort order the import of the file fails with this errormessage:

![Bildschirmfoto-20190902100052-1342x1544](https://user-images.githubusercontent.com/3774978/64112659-595ca180-cd88-11e9-82e6-f1d1dba91822.png)

**Comment by PLanB2008** [comment]
This should be solved with the current sophomorix-version. Please try and provide feedback.
