### ISSUE TITLE
Printing of passwordlists ends with 404 error in linuxmuster-webui7 (1.0.95-1)

### ISSUE THREAD

**Issue by foer** [linuxmuster/linuxmuster-webui7#115]
After sending a password printing request, the webui redirects to a 404 Site. This is a nasty showstopper and should be fixed immidiately.

![404](https://user-images.githubusercontent.com/3774978/64851663-23d17700-d618-11e9-9901-29f64472336d.jpg)

Dominik

**Comment by PLanB2008** [comment]
fixed in 5274ec63a00bcdbf86afca800e13669323571c42 and package 1.0.96-1
please confirm.
