### ISSUE TITLE
Webui/selma weird error when using passwords

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-webui7#116]
Hi, here:https://ask.linuxmuster.net/t/schulkonsole-selma-legt-keine-lehrer-an/4184/4?u=tobias
im Prinzip worum es geht:
Wenn ich "Wunschpasswort" verwenden will, dann klappt das nur, wenn alle schon existierenden ein Wunschpasswort haben, nicht, wenn ich bei einem neuen Lehrer damit anfangen will.

Außerdem: Das Wunschpasswort muss den Regeln entsprechen, die man aber auf der Seite nicht sehen kann. Die Rückmeldung jeweils "Required data missing" ist weder deutsch noch hilfreich in irgendeinem der obigen Fälle.

VG

**Comment by PLanB2008** [comment]
Ist mir bereits bekannt. Das Problem tritt auch auf,wenn  keine Lehrer wunschlogins verwendet werden.

Fehlenden Übersetzungen gerne mal zentral in einem Ticket sammeln. 

Ich denke an der Stelle können wir die Prüfung lockern, falsche Eingaben werden dann aber immernoch richtigerweise beim Import fehlschlagen.

Letztendlich bearbeiten wir hier auch nur eine importliste, keine Datenbank.

**Comment by kiarn** [comment]
Hello,

I'm working on it : 

![2019-10-01_21-47](https://user-images.githubusercontent.com/10401079/65995228-55aa6080-e495-11e9-9a97-4a3e3af290ba.png)

But it's a very long process to factorize and customize all possible errors : the goal is to have all tests and error messages i na single place.

The "desired password problem" is already solved is the branch "validation".

**Comment by kiarn** [comment]
Fixed in https://github.com/linuxmuster/linuxmuster-webui7/commit/fec9413743c6c7d9b6cf0110e2f2a9f1b5e24577
