### ISSUE TITLE
Students should be able to log in to WebUI to change Passwort and view Quota

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-webui7#119]
This is a Feature Request:
i would like it very much if Students could log into WebUI to change their Password and view their Quota.
Changing Passwords through WebUI istead of mechanisms of the Client OS has a big Advantage: you can state Password Policies before changing Passwords (which is already done in WebUI: Thumbs up for that :-)  ).

Yours

Holger

**Comment by foer** [comment]
+1

**Comment by jolly-jump** [comment]
+1

**Comment by jolly-jump** [comment]
please, please, it is not so complicated. I use the workaround: 
```
sed -i "s/(sophomorixRole=schooladministrator)/(sophomorixRole=schooladministrator)(sophomorixRole=student) /" /usr/lib/linuxmuster-webui/plugins/lmn_auth/api.py
```
but if it should be configurable then I don't know how to do it. 
For the fix entry I can pull a request....

**Comment by kiarn** [comment]
@jolly-jump : it's really more complicated as what you think. We have to change the complete auth process and uid/gid isolation to execute some commands.

The good news is : this is 99% fixed, we are just waiting some changes in sophomorix and more tests to finalize this. I hope it will comes the next weeks. We didn't forget this issue, but it was a hard work : https://github.com/linuxmuster/linuxmuster-webui7/blob/cd5ea613324bf02ee51901568449dc080d4dbd07/usr/lib/linuxmuster-webui/plugins/lmn_auth/api.py#L130

**Comment by jolly-jump** [comment]
ok, didn't know either of this. Thanks for working on it!

**Comment by kiarn** [comment]
Implemented since the last release.
