### ISSUE TITLE
Skip firewall configuration does not skip it

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#12]
I've checked "Skip Firewall Configuration" but the setup still wants to set up the firewall:

![auswahl_058](https://user-images.githubusercontent.com/708888/39814301-fb78b850-53bd-11e8-9444-21b3695d17b3.png)

**Comment by netzint** [comment]
can you please post the /tmp/setup.ini file?

**Comment by zefanja** [comment]
```bash
root@server:~# cat /tmp/setup.ini 
[setup]
servername = server
domainname = linumxuster.lan
adminpw = a
skipfw = True
```

**Comment by netzint** [comment]
This looks like a bug in linuxmuster-setup.

skipfw = True > that's ok.

**Comment by zefanja** [comment]
The thing is `linuxmuster-setup -s` does work like expected :)

**Comment by netzint** [comment]
Yes, but probably not in unattanded mode:

The WebUI calls: 'linuxmuster-setup -u -c /tmp/setup.ini ..'

**Comment by netzint** [comment]
Ticket Created: https://github.com/linuxmuster/linuxmuster-base7/issues/20

**Comment by zefanja** [comment]
Right, just tested it.
