### ISSUE TITLE
password view of student should show username

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#123]
When beeing in
Unterricht - >Session -> (Zahnrad) -> Erstpassword anzeigen

there should be 

1) also the username displayed.
2) The window showing username and password should be larger
(lage white frame aroud the data)
The students take pictures of their data, and should not see other data

**Comment by PLanB2008** [comment]
Is this really a use case?

Whould it be suitable to make the frame as big as the user details window? But also in this case there would be some data at the bottom.

We would have to add a blank page around the whole frame to get rid of any other data. 

Other than that: I'll add the username, this seems to be an obvoius improvement.

**Comment by PLanB2008** [comment]
Fixed in 3e3783f8c516c9f9b31461b9d05f5c7c316539ca

![grafik](https://user-images.githubusercontent.com/26460239/74930801-a2f48380-53de-11ea-9bc9-d1ca8c49472f.png)
