### ISSUE TITLE
select and unselect all users in session for exam changes all users 

### ISSUE THREAD

**Issue by roesslerrr** [linuxmuster/linuxmuster-webui7#124]
Hello!

Some users in a session are in exam-mode und you want to stop the exam-mode for this users.

If you select exam-mode for ALL users of the session and then unselect ALL users, then the boxes of the exam-users are empty and yellow. 
If you save this preferences the exam-mode is tried to stop for ALL users of the session, not only the yellow marked. But this can only be done for the exam-users. 
No problem (the sophomorix-command only can't be stopped), but this takes much more time than necessary.

Greetings - Rainer

**Comment by PLanB2008** [comment]
In general this is the correct behaviour. If sophomorix takes to long to recognize these users arent in exam mode, we could update this.
The concept is, if you hit the save button everything gets executed as stated, no matter which previous status the user had.

**Comment by PLanB2008** [comment]
@jeffbeck could you improve the speed by checking if a user is in exam mode before? If its impossible I could look into my code, but I think it would be better to let sophomorix deal with it.

**Comment by kiarn** [comment]
Resolved in new session plugin.
