### ISSUE TITLE
exam user password cannot be reset by webui (was so before)

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#125]
when a user is in the exam-mode, password change (set firstpassword, ...) is not possible anymore.

Reason shown by webui: user is in exam mode

This is teature is necessary, when the teacher hast started an exam and one of the participants has forgotten his password

**Comment by kiarn** [comment]
Is it related to https://github.com/linuxmuster/sophomorix4/issues/104 ?
I mean : do you need to first implement something in sophomorix so  that we could correct this ?

**Comment by PLanB2008** [comment]
@jeffbeck 

I wasn't sure if its wise to change the password during the exam. Afterwards the password of the users differ from its exam account.
I could allow this again but I think its confusing.

**Comment by jeffbeck** [comment]
It is big trouble if a teacher started an exam. And one student doesn't remember this password.

The student cannot participate in the exam, the teacher has to end exammode to change password. And restart exam again.
That takes to much time in an exam situation.


If the student gets confused (old password is still valid) this can be easily fixed in the next 'normal' non-exam situation.

**Comment by jeffbeck** [comment]
> Is it related to [linuxmuster/sophomorix4#104](https://github.com/linuxmuster/sophomorix4/issues/104) ? I mean : do you need to first implement something in sophomorix so that we could correct this ?

The setting of a password works also in exam mode:

sophomorix-passwd --user <user> --pass 'Muster!7'

The password check if the firstpassword is working for the exam user, use the exam account name:
sophomorix-passwd --test-firstpassword -u <user>-exam

**Comment by kiarn** [comment]
This is solved in the new session plugin.
