### ISSUE TITLE
teacher: sharing files with pupils ends up in a loop if teachers has forgotten to load a file 

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#128]
Logged in as a teacher, have chosen class room -> teaching -> sharing (austeilen)

When the teacher has forgotten to upload a file which he wants to share and clicks sharing -> the webUI ends up in an endless loop.
I can close the browser and login in again. But I think the WebUI should terminate the process.

Chris

**Comment by kiarn** [comment]
Hello Chris,

Thanks for your report, it's fixed. F5 is althought your friend in this case ;)
