### ISSUE TITLE
Druck-Daten: Einträge werden nicht angezeigt

### ISSUE THREAD

**Issue by white-rabbit07** [linuxmuster/linuxmuster-webui7#129]
Eine Rückfrage zu dieser Datei:
–> https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/config-devel/master/school.conf.master

Da gibt es viele Einträge wie z.B. die ganzen URL...= , die es in meiner school.conf gar nicht gibt.
Wenn ich als global-admin unter Schuleinstellungen --> Druck-Daten etwas eintrage, ist es nach dem nächsten Aufruf der Seite wieder verschwunden.

Wenn ich da was eintrage und Speichern klicke, wird der Eintrag zwar gezeigt, wenn ich oben nur die Registerkarte wechsele und dann zurück auf Druck-Daten kehre. Aber wenn ich einen ganz anderen Menupunkt links anwähle und anschließend zurück zum Menupunkt Druck-Daten komme, ist der Eintrag erneut verschwunden. Das ist also weiterhin ein kleiner Bug…

Müssen in der school.conf schon alle Einträge vorhanden sein oder nicht? In der Version im github steht ganz oben außerdem:
TRUE/FALSE must be used to configure Booleans
In meiner school.conf steht allerdings teilweise:
SURNAME_FIRSTNAME_REVERSE=no
anstatt:
SURNAME_FIRSTNAME_REVERSE=FALSE << Ist das ein Problem?

**Comment by jeffbeck** [comment]
Die von dir verlinkte master Datei zeigt alle **zuässigen** Einträge an. Sie müssen aber nicht da sein.

Wenn ich das mit sophomorix teste, dann trage ich das per Editor ein.

Bin mir nicht ganz sicher ob die webui da auch noch was machen muss.

Ob true/yes/1/TRUE haben wir so lange diskutiert, bis ich es einfacher fand zu sagen: alles ist erlaubt (wie bei samba)
Falls das nicht so ist, bitte melden.

**Comment by white-rabbit07** [comment]
Hi. Das heißt, dass der Eintrag **vollständig** angelegt und in der school.conf eingetragen wird, wenn ich z.B. die moodle-URL einstelle, ja? Oder muss ich es mir so vorstellen, dass nach dem Eintrag "moodle-url=" gesucht wird und hinter dem "=" dann der Eintrag gemacht wird? 

Ich trage viele Dinge auch **direkt** in die conf-Datei ein. Das Problem ist im Moment aber: Da meine .conf gar nicht alle Zeilen beinhaltet, die es gibt, kann ich so natürlich auch nicht erfahren, welche möglichen Einträge es gibt

**Comment by jeffbeck** [comment]
Zum zweiten Teil:
Die neuen parameter werden programmiertechnisch in der school.conf.master bekanntgegeben,
Seit kurzem auch im Paketfeed: 
https://ask.linuxmuster.net/t/v7-beta-paketfeed/3438/106

Am besten wäre natürlich, wenn die webui, die master einliest, eine schöne Beschreibung liefert und dann die Zeilen nachträgt.

Das wird sicher mal passieren, aber geht prinzipbedingt nur mit Verzögerung, weil unsere Tester Konsolen und Editoraffin sind und die tested-GUI Features erst später für die anderen ins Webui hochgespült werden.

Vielleicht kann das Webui-Team auch noch was zum Stand sagen.

**Comment by PLanB2008** [comment]
Die Webui legt die Werte selbständig an wenn diese gesetzt werden. Allerdings muss von unserer Seite definiert werden welche Fehler es zum ausfüllen gibt.
Theoretisch könnten wir dies auch auslesen, ich denke aber das wäre overkill da hier nicht zu häufig neue Werte zu erwarten sind.
Zudem würde ein automatisches bestimmen der Fehler auch eine ausgewogene Übersetzung der Attribute verhindern.

**Comment by kiarn** [comment]
I think this discussion is not relevant anymore. The bug mentioned in the first post is already solved and @PLanB2008 answered about the rest. Please feel free to open it again if I'm wrong.
