### ISSUE TITLE
There is no way to cancel the setup

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#13]
On the last screen there is no way to cancel the setup (e.g. something went wrong with `linuxmuster-setup`). There is just a spinner and the command line output.

**Comment by PLanB2008** [comment]
Well I'm not sure how to tackle this problem. The installation process is kind of complex and at the moment it would be best to start over if something goes off the rail during this process - so a abort button would not really help to start the process over again.
Without the option to rerun the setup and get a working environment afterwards a camcel button wouldn't help.
I'll label this for the future.

**Comment by cweikl** [comment]
Using WebUI Version 1.0.18-41 I have chosen docker, firewall-config and opsi, having forgotten to start the opsi VM. The setup is successful, but I only the the end of the log file in the WebUI and the the circle as a symbol for ongoing installation ist still turning. I cannot close the window. It is a bit confusing. Closing the browser and starting it agains brings me to the configured UI.

**Comment by PLanB2008** [comment]
I added a summarize page before the installation process. During the provisioning process theres nothing we can do to stop the installation (similar to terminal).

Maybe we could add a for the external services, check if they are reachable before start real provisioning process...

**Comment by jolly-jump** [comment]
see #74, similar

**Comment by kiarn** [comment]
I think it's the same conclusion as #74 .
Once the setup is done, it's not possible to undo it.
