### ISSUE TITLE
Timeout when printing passwords

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-webui7#130]
sophomorix-samba Version: 3.77.2-1
linuxmuster-webui7: Version: 1.0.139-1

- logged in as teacher, 
- does not respond for a looong time.
- in the end the PDF that comes back is really a text/html which says Server error with traceback:
```
AttributeError: 'GateMiddleware' object has no attribute 'auth_info'
```

**Comment by kiarn** [comment]
Hello @jolly-jump 

Thanks.
Already fixed : https://github.com/linuxmuster/linuxmuster-webui7/commit/8e374a812ed1351a18c61f87ea4a8aa97fba95e0

Must just be published.
