### ISSUE TITLE
Another byte encoding issue in list upload

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#135]
Trying to upload a students list via webui (list management) fails:

<img width="649" alt="grafik" src="https://user-images.githubusercontent.com/26460239/81271871-f45ef700-904c-11ea-928c-0e49bdf639db.png">

**Comment by kiarn** [comment]
Does it work with 'rb' instead of 'r' ?

**Comment by PLanB2008** [comment]
I assume it'll work but I can't test it at the moment. I'll provide more feedback asap.

**Comment by kiarn** [comment]
The only way I was able to reproduce this was with an empty csv file, but not for other usual encoding types, or do you know other cases ?

**Comment by kiarn** [comment]
I thin k we can close it, https://github.com/linuxmuster/linuxmuster-webui7/commit/3083684829a3df25eb7cf667116e6d26d85803ea should have fixed it.
