### ISSUE TITLE
name format in webui main page

### ISSUE THREAD

**Issue by cibomato** [linuxmuster/linuxmuster-webui7#138]
In webui at the main page under "Kontoinformationen" - Name: the chosen format 
_first name, family name_ e.g. _Max, Mustermann_
with a comma in between looks strange.
I'd either choose:
_family name, first name_ e.g. _Mustermann, Max_
or
_first name family name_ (without comma) e.g. _Max Mustermann_
Cheers,
Jochen

**Comment by kiarn** [comment]
Hello @cibomato,

Yes, it looks weird, I removed the comma, but I let the issue open to let the others give their opinions, because it's relative to local culture.

**Comment by kiarn** [comment]
I made a commit for the second option, and removed the comma, I think we can close it.
Please see : https://github.com/linuxmuster/linuxmuster-webui7/commit/cacb5a4bcba6163735a20f1b81050933007b1547
