### ISSUE TITLE
Navigation initial setup

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#14]
It is possible to jump to any screen for the initial setup and skip the screens before.

![peek 2018-05-09 19-40](https://user-images.githubusercontent.com/708888/39815011-e470bd9e-53c0-11e8-8110-18d4a4125e39.gif)

**Comment by PLanB2008** [comment]
I'll close this issue because its just missusing the interface. You can always go back and for so I don't see a point in limiting this.
