### ISSUE TITLE
Bug in Webui when editing Linbo partition due to encoding problems

### ISSUE THREAD

**Issue by goeba** [linuxmuster/linuxmuster-webui7#143]
Hi,
I've got the following error (latest Linuxmuster 7, updated May 2020):

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_linbo/views.py", line 88, in handle_api_images
    'description': open(desc_file, 'rb').read().decode(mime.from_buffer(open(desc_file).read())) if os.path.exists(desc_file) else None,
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xfc in position 35: invalid start byte

The dialog that showes this message said "this is likely a bug"

Regards,
Andreas

**Comment by kiarn** [comment]
Hello Andreas,

Thanks for the report, it's already solved in the testing branch, we must push a new package ASAP.

Regards,

Arnaud
