### ISSUE TITLE
Ghost session

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#145]
Hello,

When a teacher creates a session, and then delete it, it remains a ghost session without id.
I found many reasons for this : 

https://github.com/linuxmuster/linuxmuster-webui7/blob/8c945d3347b07c94e93ad0d69dbe97fd4e13d533/usr/lib/linuxmuster-webui/plugins/lmn_session/views.py#L34 : even if there's no session, an object is added to the sessionList, and returned to angularjs.

https://github.com/linuxmuster/linuxmuster-webui7/blob/8c945d3347b07c94e93ad0d69dbe97fd4e13d533/usr/lib/linuxmuster-webui/plugins/lmn_session/resources/js/controllers/session.controller.coffee#L318 : even if the session count is 0, `$scope.sessions` is set to `resp.data` which contains one element. Is there a reason for this ?

Then, with one element in the list, `ng:repeat` shows one incomplete session.

Thanks

Arnaud

**Comment by PLanB2008** [comment]
I'll look into this.

The session module is a fairly complicated plugin, in addition it was the first one I wrote, so there is the possibility a lot of things could be done easier.
I'm gonne fix it :)
