### ISSUE TITLE
School Console Title

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#148]
Just an idea: 

Currently the webUI has the following website title, e.g. "Students | server.domain.com". What about displaying the school name / school short name / abbreviation instead of the server FQDN?

**Comment by kiarn** [comment]
Nice idea, but it needs some work, since we have to load each time the linuxmuster config before the page shows.

**Comment by kiarn** [comment]
It's quite done, we just have to clarify some changes for the upcoming features.
