### ISSUE TITLE
Input is not validated

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#15]
There are some inputs that are not validated or required (compare to `linuxmuster-setup`):

* server hostname
* domain
* Admin password (can be anything)

**Comment by PLanB2008** [comment]
Should be fixed in current code. Package will be updated soon

**Comment by zefanja** [comment]
Could you please add some hints which characters are expected in a strong password?

"Muster!" does work in the CLI-Setup, but not in the webUI. It would be nice if both can share the same test for a good / strong password.

**Comment by PLanB2008** [comment]
Fixed with  60c6c2a28cf9b13c03eaabc4d03c091e873b0e46

**Comment by zefanja** [comment]
In the latest version in `https://.../view/lm/init/school` input validation is not working if there is no input. It validates only if you enter something.

Error in the console: `TypeError: _this2.ini is null`
