### ISSUE TITLE
Modal dialog does not disappear when deleting projects

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-webui7#150]
When I delete a project as a teacher in the webui,
the shown dialog does not disappear, while the new modal dialog ("do you really...")
already appears below.
Just clicking next to the first dialog lets it disappear and one can click to agree to really delete.
TRied chromium and icecat as browsers.

**Comment by kiarn** [comment]
Hello @jolly-jump,

It's already solved here : https://github.com/linuxmuster/linuxmuster-webui7/commit/f8dbaade2786d97e4abacc4f3d6ecb2b20d6a891
But not published.

Arnaud
