### ISSUE TITLE
Testing webui with 20.04

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-webui7#159]
I upgraded a test system to 20.04. After reboot `dpkg-reconfigure linuxmuster-webui7` was necessary. This runs without errors. Webui service does not start. Manually invoking
`/usr/bin/python3 /usr/local/bin/ajenti-panel -d --stock-plugins --plugins /usr/lib/linuxmuster-webui/plugins`
causes the following error:
`<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 152, got 144`
Downgrading greenlet to 0.4.15 fixed this: `pip3 install greenlet==0.4.15`
After that webui service starts, users are able to login. It seems to work. Nevertheless, further testing is required.

**Comment by kiarn** [comment]
This is already solved in Ajenti, please see : https://github.com/ajenti/ajenti/commit/bbce12fd167d3fa3f5d29244731eb79d69ef24d9

Next version should soon be released.
You can also test with : `/usr/bin/python3 /usr/local/bin/ajenti-panel -dev --stock-plugins --plugins /usr/lib/linuxmuster-webui/plugins`
