### ISSUE TITLE
Option for UseMinimalLayout in Linbo configuration

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#161]
Hey everyone,

The new Linbo GUI adds a new parameter to the start.conf file: `UseMinimalLayout`.
It  is of type Bool and controls how the GUI looks.
It would be nice to have a setting for this added to the input mask in the webui :) 
(Somewhere over here)
![Screenshot from 2020-12-22 18-49-08](https://user-images.githubusercontent.com/30153207/102918174-be10a380-4486-11eb-8ae6-c3057167298f.png)

Regards
Dorian

**Comment by kiarn** [comment]
Hello @CodeCrafter912,

Default value is false ?

Regards,

Arnaud

**Comment by dorianim** [comment]
@kiarn 
Yep, default is false

**Comment by dorianim** [comment]
That was fast, thank you :)
