### ISSUE TITLE
Linbo config option for background color

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#164]
It would be nice to have an option for the Linbo background color over here:
![image](https://user-images.githubusercontent.com/30153207/104368317-33b6df00-551c-11eb-82de-43df38544860.png)
The color has to be set via the `BackgroundColor` parameter and must be a html hex color ([example can be found here](https://www.w3schools.com/colors/colors_picker.asp)).
It is important though, that the "#" before the color is removed, as # stands for a comment in the linbo start.conf (`#0f0f0f` -> `0f0f0f`)

In addition to that, the hint "The color of the foreground will be adjusted automatically" would be nice :)

Regards, Dorian

**Comment by kiarn** [comment]
I think it's done, but it must be tested. Is that a problem if the option `BackgroundColor` is empty in the `start.conf` file ?

E.g. : 

```
BackgroundColor = 
```

**Comment by dorianim** [comment]
Thank you :)
Should not be a problem. I will test it and if it actually is a problem, I will fix it.
