### ISSUE TITLE
Missing ntacl in deb package

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#168]
Hello,

The file `/usr/lib/linuxmuster-webui/etc/webuiUpload.ntacl` is missing in the deb packages, breaking the update process : 

```
dpkg -L linuxmuster-webui7 | grep ntacl
```

is empty.

As workaround, I told to do the following : 

```
wget -P /usr/lib/linuxmuster-webui/etc/ https://raw.githubusercontent.com/linuxmuster/linuxmuster-webui7/release/usr/lib/linuxmuster-webui/etc/webuiUpload.ntacl
apt install -f
```

Thanks

Arnaud

**Comment by PLanB2008** [comment]
This is fixed in 137c97edf02d64b614dfaa0c298cd1c33f8df34b

I moved it into the initial installation hookdir. On new systems it should run now without a flaw. On system which still have this bug I suggest running

`/usr/lib/linuxmuster-webui/etc/create_webuiUploadFolder.sh`

**Comment by baumhof** [comment]
Hello,

i just installed webui 1.0.159-1 from testing repo: the Problem persists. ntacl is still missing.
I have to wget it and reinstall with apt install -f

Yours 
Holger

**Comment by kiarn** [comment]
Hello Holger,

Since the repo is not maintained anymore, we are migrating this to Github : https://github.com/linuxmuster/deb
It's not finished yet, and we must find a consensus between all dev ( hopefully the next weeks ) in order to publish this.
There's already a new version available for testing : https://github.com/linuxmuster/deb/tree/main/packages/linuxmuster-webui7/lmn7-testing

and for stable : 
https://github.com/linuxmuster/deb/tree/main/packages/linuxmuster-webui7/lmn70

( yes, the distribution will be lmn70 and not lmn7, because we are preparing lmn71 at this time ).

The whole migration is still under tests, and the documentation for this will come soon.

Arnaud
