### ISSUE TITLE
Wrong ACLs to delete files 

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#172]
Hello,

It's currently not possible to delete any file as teacher in his home directory `/srv/webuiUpload/default-school/teachers/masskrug`. The Webui shows the deleted file as "deleted" because it simply remove the entry in the JS-Object, but the file is not deleted on server side.

The reason is that the acl are not set correctly for this situation : 

- `Webui` runs with uid `masskrug` and gid `role-teacher` --> I get silently `PermissionError` with `Python`
- `Webui` runs with uid `masskrug` and gid `users` --> it works

All files in `/srv/webuiUpload/default-school/teachers/masskrug` are set with gid `users`, I hope it's the right group.

**Comment by PLanB2008** [comment]
I don't get it.

The permissions (now correctly fixed for fresh installs in: 137c97edf02d64b614dfaa0c298cd1c33f8df34b ) allow everyone in role-teacher to create and delete everything).

Deleting files in the upload dialogue should delete files in /srv/samba/default-school/teachers/masskrug/transfer or whatever. These acls should be correct from the beginning.

Could you go into detail a little more?

**Comment by kiarn** [comment]
> Deleting files in the upload dialogue should delete files in /srv/samba/default-school/teachers/masskrug/transfer or whatever. These acls should be correct from the beginning.
> 
> Could you go into detail a little more?

Yes, I must edit my first post because I used the wrong path to describe the problem.
We are speaking of `/srv/samba/default-school/teachers/masskrug/transfer` and not `/srv/webuiUpload`, sorry for the confusion.

So, basically, a teacher in `role-teacher` group cannot delete a file in his home transfer file. It works as group `users` but not as group `role-teacher`.

**Comment by PLanB2008** [comment]
Hmmm but  why is this the case? When I upload a file via webui I get the following permissions:

```
root@server ..ba/schools/kbrs/teachers/hume/transfer # getfacl andy.jpeg
# file: andy.jpeg
# owner: 3000000
# group: users
user::rwx
user:root:rwx
user:3000000:rwx
user:3000022:rwx
user:3000024:rwx
user:3000037:rwx
user:LINUXMUSTER\134hume:rwx
group::---
group:users:---
group:LINUXMUSTER\134global-admins:rwx
group:\134owner\040rights:rwx
group:LINUXMUSTER\134kbrs-admins:rwx
group:LINUXMUSTER\134hume:rwx
mask::rwx
other::---
```

These permissions are set by 

```
# share data
  sophomorix-transfer --from-unix-path /srv/upload/... --to-user <user1>,<user2>-exam, ... --subdir <dir>
```

Having the right user attribut set it should be possible to delete. The group attribute is not neccessary.

**Comment by PLanB2008** [comment]
Running the same command as this user works as well...

```
LINUXMUSTER\hume@server:/srv/samba/schools/kbrs/teachers/hume/transfer$ ls
andy.jpeg  andy.jpeg2  test.py
LINUXMUSTER\hume@server:/srv/samba/schools/kbrs/teachers/hume/transfer$ more test.py
import os

os.unlink('andy.jpeg')
LINUXMUSTER\hume@server:/srv/samba/schools/kbrs/teachers/hume/transfer$ python3 test.py
LINUXMUSTER\hume@server:/srv/samba/schools/kbrs/teachers/hume/transfer$ ls
andy.jpeg2  test.py
```

**Comment by kiarn** [comment]
Yes, it's because all teachers are member of the group `users`. I don't understand what is happening and I'm trying to test further. `users` is a local group, is it possible that the permission on a local group have precedence over a samba user ?

**Comment by kiarn** [comment]
So I made some others tests as `teacher:role-teacher`. The problem is the test if the file exists here : https://github.com/linuxmuster/linuxmuster-webui7/blob/7b7e8466b52b81da0f42937c965304dd085acd9f/usr/lib/linuxmuster-webui/plugins/lmn_common/views.py#L104

`os.path.exists` will fail if it can not perform an `os.stat` on the file or the directory.
`os.path` works fine for `/srv/samba`, `/srv/samba/schools`, `/srv/samba/schools/default-school` but will fail with `/srv/samba/schools/default-school/teachers` (and the other directories following) : 

```
06.05.2021 22:40  [worker 32174]          gate.py:120   ERROR    Unhandled endpoint error at /api/lm/remove-file
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aj/api/endpoint.py", line 71, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/srv/dev/linuxmuster-webui7/usr/lib/linuxmuster-webui/plugins/lmn_common/views.py", line 110, in handle_api_remove_file
    print(f'DEBUG {path} {os.stat(path)}')
PermissionError: [Errno 13] Permission denied: '/srv/samba/schools/default-school/teachers'
```

In my environment, I have the follwing ACLs : 

```
$ getfacl /srv/samba/schools/default-school         
getfacl: Removing leading '/' from absolute path names
# file: srv/samba/schools/default-school
# owner: 3000004
# group: root
user::rwx
user:3000018:r-x
user:3000020:r-x
user:3000021:r-x
group::---
group:root:---
group:UNPEUD\134domain\040admins:rwx
group:UNPEUD\134s_default-school:r-x
group:UNPEUD\134students:r-x
group:UNPEUD\134teachers:r-x
mask::rwx
other::---
default:user::rwx
default:user:3000004:rwx
default:user:3000019:rwx
default:group::---
default:group:root:---
default:group:UNPEUD\134domain\040admins:rwx
default:group:UNPEUD\134admins:rwx
default:mask::rwx
default:other::---

$ getfacl /srv/samba/schools/default-school/teachers
getfacl: Removing leading '/' from absolute path names
# file: srv/samba/schools/default-school/teachers
# owner: 3000000
# group: users
user::rwx
user:root:rwx
user:3000000:rwx
user:3000019:rwx
user:3000021:r-x
user:3000022:rwx
group::---
group:users:---
group:UNPEUD\134admins:rwx
group:UNPEUD\134teachers:r-x
group:UNPEUD\134global-admins:rwx
mask::rwx
other::---
default:user::rwx
default:user:root:rwx
default:user:3000000:rwx
default:user:3000019:rwx
default:user:3000022:rwx
default:group::---
default:group:users:---
default:group:UNPEUD\134admins:rwx
default:group:UNPEUD\134global-admins:rwx
default:mask::rwx
default:other::---
```

Are you able to delete effectively a file in your Webui ?

**Comment by kiarn** [comment]
More tests : 

```
# Test isdir / isfile as teacher : 
DEBUG /srv True
DEBUG /srv/samba True
DEBUG /srv/samba/schools True
DEBUG /srv/samba/schools/default-school True
DEBUG /srv/samba/schools/default-school/teachers False
DEBUG /srv/samba/schools/default-school/teachers/kiar False
DEBUG /srv/samba/schools/default-school/teachers/kiar/transfer False
DEBUG /srv/samba/schools/default-school/teachers/kiar/transfer/file.pdf False

# Test os.stat as root/root
$ ps -p 28561 -o user:20,group=GROUP # AS root/root
USER                 GROUP
root                 root

>>> os.stat("/srv/samba/schools/default-school")
os.stat_result(st_mode=16888, st_ino=4325381, st_dev=2097, st_nlink=10, st_uid=3000004, st_gid=0, st_size=4096, st_atime=1620317826, st_mtime=1618557418, st_ctime=1619799224)

>>> os.stat("/srv/samba/schools/default-school/teachers") # WORKS
os.stat_result(st_mode=16888, st_ino=4326338, st_dev=2097, st_nlink=10, st_uid=3000000, st_gid=100, st_size=4096, st_atime=1620330813, st_mtime=1616337166, st_ctime=1619799225)

# Change group to role-teacher
>>> os.setgid(3001056) # change gid to role-teacher

$ ps -p 28561 -o user:20,group=GROUP # AS root/role-teacher
USER                 GROUP
root                 UNPEUD\role-teacher

>>> os.stat("/srv/samba/schools/default-school/teachers") # WORKS
os.stat_result(st_mode=16888, st_ino=4326338, st_dev=2097, st_nlink=10, st_uid=3000000, st_gid=100, st_size=4096, st_atime=1620330813, st_mtime=1616337166, st_ctime=1619799225)

# Change uid to teacher
>>> os.setuid(3001042) # change uid to teacher1, same if I test with another teacher

$ ps -p 28561 -o user:20,group=GROUP
USER                 GROUP
UNPEUD\kiar          UNPEUD\role-teacher

>>> os.stat("/srv/samba/schools/default-school/teachers") # FAIL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
PermissionError: [Errno 13] Permission denied: '/srv/samba/schools/default-school/teachers'
```

If i do the same with the `pysmbclient` library (using kerberos), I have no problem, so I'm slowly thinking that the `os` module in `python` has problem to read some ACLs.

**Comment by PLanB2008** [comment]
Well to be honest using pysmbclient or implementing this in sophomorix is the only long term solution anyway.

Deleting files this way only works when the teacher home is a local path. I think the easiest way to tackle this would be to implement a delete function in sophomorix-transfer and use this to delete a given file.

Using pysmbclient could be seen as a long term solution but we rely on sophomorix a lot in this module for sharing and collecting files so we need to use sophomorix anyway...

What do you think?

**Comment by kiarn** [comment]
I get the same permission error with `os.unlink` so I think we can only provide a quick fix with a new option in `sophomorix-transfer`.

**Comment by kiarn** [comment]
Using `smbclient` seems to solve the problem.
