### ISSUE TITLE
Add functionality to add rooms to printer groups

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#173]
Add functionality to add rooms to printer groups inside the webui.

**Comment by kiarn** [comment]
I'm asking some questions to fully understands how `sophomorix-group` works :

https://github.com/linuxmuster/sophomorix4/issues/131

This should be done soon.

**Comment by kiarn** [comment]
I checked some points with `sophomorix` and there's some work to do so it works : 

https://github.com/linuxmuster/sophomorix4/issues/132
https://github.com/linuxmuster/sophomorix4/issues/133

**Comment by kiarn** [comment]
I add the possibilty to include a room into a printer group.
This is actually possible for project too, and I think it's not necessary to have this for project.
If @PLanB2008 confirms that we do not need this for project, I will limit the use only for printer groups.

**Comment by dorianim** [comment]
Cool :D 
This will be very helpful for many people and should be announced in ask (best over here: https://ask.linuxmuster.net/t/fragen-zum-neuen-anmeldescript-fuer-linuxclients-linuxmuster-linuxclient7/7406 or here: https://ask.linuxmuster.net/t/linuxmuster-linuxclient7-muessen-drucker-ueber-gpos-installiert-werden/7921 )

I dont think, this is necessary for projects, at least I cannot come up with a possible usecase.

**Comment by kiarn** [comment]
> This will be very helpful for many people and should be announced in ask 

It's nothing new, just a `sophomorix-group --addmembergroups ROOM --group PRINTER`.
But we should discuss about announcements when you are back, because we first need to publish all changes since 10 months (!) and test it.
  
> I dont think, this is necessary for projects, at least I cannot come up with a possible usecase.

Allow the access to a share only over a room ? E.g. access to `p_arts` in the arts rooms and nowhere else.

**Comment by dorianim** [comment]
> It's nothing new

It is new that it is possible in the webui, though :)

> we first need to publish all changes since 10 months

👍

> Allow the access to a share only over a room ? 

This is very interesting! You've got a point there, maybe it would make sense to also enable it for projects.
