### ISSUE TITLE
Add support for editing the prestart script

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#176]
Add support for editing the prestart script of an image. This could be achieved by simply adding another tab to the image editing popup:
![image](https://user-images.githubusercontent.com/30153207/115688136-2733f500-a35b-11eb-92af-182f86c177b0.png)

**Comment by kiarn** [comment]
Can you please describe which file to edit ( path, extension, name model ), and from which version of linbo we can use it ?

**Comment by dorianim** [comment]
It is similar to the postsync script:  
\<imagename\>.cloop.prestart

**Comment by PLanB2008** [comment]
Thats not true. This seems to be the first file which has do be written without the .cloop extension so it should be

`<imagename>.prestart`

https://github.com/linuxmuster/linuxmuster-linbo/commit/4759d9e24f02e3b06b8365015a97fee8d3a3a13e#diff-94e15f7aab87c8ae1aa92e19b55c796192850c2b3c3cc5ecf62344caa144a3f2R1542

Where `/mnt/.linbo ` is a textfile containing the imagename (eg. in Windows C:\.linbo)

**Comment by dorianim** [comment]
Yep, looks like you are right. Apologies for the confusion :)

**Comment by kiarn** [comment]
Ok, thanks. And what are the right permissions for a `IMAGE.prestart` script : 644, 664, other ?
