### ISSUE TITLE
linuxmuster-imort-devices multi-school

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#178]
I don't know if this is still relevant, but I'm opening this, so it is not forgotten:
linuxmuster-import-devices now needs the parameter `-s` followed by the school in multi-schools.

**Comment by kiarn** [comment]
Ok, but as I see in the source code of `linuxmuster-import-devices`, it's a non-breaking change : without the `--school` argument, `default-school` is chosen.
So it's only necessary to add it in multischool env, I think @PLanB2008 will make it.

**Comment by PLanB2008** [comment]
implemented in 83b75de6178f0cc572c73b4964d500e8c788959c
