### ISSUE TITLE
Unwanted behaviour in Group Menu

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#179]
![grafik](https://user-images.githubusercontent.com/26460239/117439358-08c12280-af33-11eb-97f1-40c6816c0345.png)

Its possible to remove students from a class via the group edit menu. This shouldn't be possible at all. Also making a student a admin is an unwanted behaviour. 

I suggest  

- removing delete project at all in the class details.
- removing make admin
- removing options to remove hidden and joinable 
- only allow removing teachers from the class
- only allowing add teachers to a class

**Comment by kiarn** [comment]
So I think I can also remove the red admin panel for a class, it's not necessary, don't you think ?

**Comment by PLanB2008** [comment]
Ya I think so, this menu does not need a lot of information I guess.
