### ISSUE TITLE
Adding a new row to an empty teachers.csv does not work

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#18]
Adding a row does not work with one click. You have to click twice (but then you get two rows):

![peek 2018-05-09 20-20](https://user-images.githubusercontent.com/708888/39816832-962e0f28-53c6-11e8-8659-093e733e9073.gif)

**Comment by PLanB2008** [comment]
fixed in f7a92e1a6b59ef2abeaf1d2e0ee08ea5f9fbadfb
