### ISSUE TITLE
Group Membership Module uses wrong attribute to determine teacher

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#180]
In group membership module you check if a member of a class is teacher by checking for _member.sophomorixAdminClass_.

This does not work in a mutlischool environment because the _sophomorixAdminClass_ is in this case <school_shortname>-teachers.

Better use _sophomorixRole_ in this case because this is the same for all teachers.

**Comment by kiarn** [comment]
I have to use `sophomorixAdminClass` in order to display the different user, but instead of using `sophomorixRole` just for some checks it's maybe better to test if `sophomorixAdminClass` ends with `teachers`.

**Comment by jeffbeck** [comment]
I want to encourage the idea to use sophomorixRole.
Thats the attribute for sophomorix to decide, if a user is teacher.
In future we might add other group names that are teachers.

**Comment by kiarn** [comment]
First of all, I fully agree with both of you, `sophomorixRole` is the right value to check, nothing to say about it. My thought was just trying to avoid performance issue into transporting a var for all users. But I just saw that `sophomorixRole` is already include in the members details, so I will simply use it as @PLanB2008 's suggest :)

Second, I don't get the point with this : 

> In future we might add other group names that are teachers.

If an user has a `sophomorixAdminClass` attribute like `*teachers`, then it should be a teacher. Why is it a problem to check this way ?

**Comment by jeffbeck** [comment]
we have some supporting 'teachers' (social workers) from our city. Not from Baden-Württemberg. 
For linuxmuster, they do the same work as teachers.
For other uses (listing their working hours, no access to marks (Zeugnisse)) they are a bit different.
So one day there might be a need to name their group city-techers with the role teachers
