### ISSUE TITLE
Preserve additional columns in students.csv

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#182]
Hi,

It would be nice, if extra columns in the students.csv (after the student id). This could be used for custom data, like a private email address. I also opened a related issue in sophomorix: https://github.com/linuxmuster/sophomorix4/issues/138

**Comment by kiarn** [comment]
Hi @CodeCrafter912 

I'm currently planning to make a separate plugin to handle all custom fields on it's own for many resources ( emails, Kürzel, school subjects, ... ).

**Comment by dorianim** [comment]
Oh, that is cool!
I'm looking forward to seeing it :D

**Comment by kiarn** [comment]
So, I made it this way ( not published yet ) : 

First of all, display the content of the cutom fields in the users details and make it editable :

![teachers-details2](https://user-images.githubusercontent.com/10401079/123541756-72e19100-d746-11eb-9bbe-e7709784211e.png)

You see "custom 1", "multi custom 1" is not pretty clear, so I have added a tab in the school settings in order to configure the title and the use of the custom fields, because each school has differents needs :

![custom_setttings](https://user-images.githubusercontent.com/10401079/123541862-ce138380-d746-11eb-846b-c4ec4641add8.png)

The custom display options are there to decide which fields could be displayed on the user's lists : 

![teachers](https://user-images.githubusercontent.com/10401079/123541969-509c4300-d747-11eb-89e5-c1846644d92c.png)

So you can see here that I choose the custom 1 ( Email ) and multi custom 1 ( school subjects ).
It's pretty awesome that `sophomorix` this flexibility, and I think many schools may need it.

**Comment by dorianim** [comment]
That is really, really cool :D
Is there also an Option for importing these using the list import?

**Comment by dorianim** [comment]
Just out of interest:
Where are you storing the names of the cutsom fields?

**Comment by kiarn** [comment]
> That is really, really cool :D

Thanks.

> Is there also an Option for importing these using the list import?

Not for the moment, and I think it must be implemented in `sophomorix`. The reason is : we need to know the `uid` of an user in order to call `sophomorix-user`. It would be complicated to parse the result of an import and then to call another command to set the custom fields.

> Just out of interest:
> Where are you storing the names of the cutsom fields?

In `/etc/linuxmuster/webui/config.yml`
I still didn't have the time to work further on it, I'll try this week-end.

Cheers

Arnaud

**Comment by dorianim** [comment]
> Not for the moment, and I think it must be implemented in sophomorix. The reason is : we need to know the uid of an user in order to call sophomorix-user. It would be complicated to parse the result of an import and then to call another command to set the custom fields.

Ok, I understand that.
Would it still be possible to at least preserve additional columns? I will use the sophomorix hook in combination with a custom script to push the data to the AD myself. It's not optimal, I know, but I need this to work somehow. The reason is that we are getting a list with all our members from our member management tool. This list includes email addresses, and I need a way to get them into the AD automatically.
Sophomorix does not care about additional columns in the students.csv but the Webui currently removes them.

**Comment by kiarn** [comment]
We must have a look at this with @PLanB2008 because he was the one who developped the import module.
It would also be a good solution for my environment.

**Comment by dorianim** [comment]
I'd linke to bump this up again.
Sophomorix has an option to create custom filter scripts:
https://github.com/linuxmuster/sophomorix4/wiki/Export-and-Filters#filters

This feature is not usable in conjunction with the webui right now, as it forces the user to provide the data in the final format.
Maybe it would be possible, to provide an "expert mode" toggle which enables users to upload csv files of arbitrary format.

**Comment by kiarn** [comment]
Hello Dorian,

I have a lot to do actually, but the new feature seems interesting, but I didn't understand how it works. We can apply a script on e.g. students.csv to create a new csv, or did I misunderstood the workflow ?
The script can be configured in school.conf, ok, this point is quite clear.
And what is the format of the awaited header ?

```
Name;Vorname;...
```

?
If you already have some informations or tests from your side it could help :)

Arnaud

**Comment by dorianim** [comment]
Hi Arnaud,
I really understood this feature when following this thread:
https://ask.linuxmuster.net/t/asv-bw-exportformat-fuer-schuelerdaten/6125/5

It basically allows you to use an abritray file as students.csv and sophomorix calls your custom script on import. This script must then convert the abritray file to a sophomorix compatible csv.

This is useful when a users school management software does not support a sophomorix compatible CSV format. So it would be nice to allow arbitrary CSV formats in the webui 🙃 

Does that help?

**Comment by kiarn** [comment]
Hi Dorian,

> It basically allows you to use an abritray file as students.csv and sophomorix calls your custom script on import. This script must then convert the abritray file to a sophomorix compatible csv.

Thanks for the description, this is the point I don't understand fully.

Given a file `export.csv` in the form : 

```
ID;Name;Type;Email;Name;Vorname; etc ....
```

This filter would just rewrite it as `students.csv` with the correct column order ? e.g. : 

```
Klasse;Name;Vorname;Birthdate; etc ...
```

?

**Comment by dorianim** [comment]
Hi Arnaud,
The filter is just a script wich recieves two arguments: 
`script <path to students.csv> <path to filtered studens.csv>`

The script can do anything with the data. 
Let me give an example:
Your student manager does not allow to change the order of the colums in the exported csv, so you would have to correct it manually before each import. With a custom filter script, you can place the unmodified file as students.csv and the filter script will correct it automatically on each import. This cpuld safe a lot of manual work if the webui allowed to upload the "malformed" csv file without modifications.

Another example is the usecase of my installation: 
We are not a school, so we don't have classes. All users are in the sane class. To reflect this, we always have to manually add a column containing the class name to the csv. A filter script could do that automatically, if we were able to just upload the unmodified csv without a class through the webui.

Does that help?

**Comment by kiarn** [comment]
Thanks for your patience. So basically, this is an upload followed by the call of `sophomorix-newfile` if a filterscript is provided ( and executable ). I've just tested, seems to work well.

**Comment by kiarn** [comment]
So I add a way to upload customs CSV and to configure the path to the filter script.
This way you can apply what you want on your custom CSV ( e.g. call `sophomorix` to register your email addresses or add a column to `students.csv` ), but the extra columns will then not be saved in the official `students.csv`.

I hope it's a good solution.

**Comment by dorianim** [comment]
Hi Arnaud,

Thank you! This will simplify our workflow a lot :D
