### ISSUE TITLE
Allow changing MAILDOMAIN of type.project

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#183]
Hi,
Currently, it is only possible to set the maildomain for admin and teacher classes in the school setting. It would be nice to have that for projects as well.
Over here:
![image](https://user-images.githubusercontent.com/30153207/124482701-dce2e180-dda9-11eb-8249-3fb3381b5973.png)

This is currently not working with sophomorix though, so no hurries :)
See: https://github.com/linuxmuster/sophomorix4/issues/141 and https://github.com/linuxmuster/sophomorix4/issues/120

**Comment by kiarn** [comment]
Hi,

Just a note for me - `school.conf` with all options : 

https://raw.githubusercontent.com/linuxmuster/sophomorix4/bionic/sophomorix-samba/config-devel/master/school.conf.master
