### ISSUE TITLE
New footer style

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#187]
Hello,

I found the footer style not pretty, so I made a `btn-lmn` class in order to ameliorate this.

Before : 

![TeachersVor](https://user-images.githubusercontent.com/10401079/126710762-65a88197-67f2-409c-baa3-cbfa8520360a.png)

After : 

![TeachersNach](https://user-images.githubusercontent.com/10401079/126710778-9ed23d0b-261f-43a3-82e3-9e21b92a0016.png)

Colors are inspired from the LMN Logo, and currently this is only in teacher view implemented.

By the way, there's a new functionality to print passwords directly for selected users ( with `sophomorix-print` ).

**Comment by dorianim** [comment]
Looks good 👌

**Comment by kiarn** [comment]
I made the button a little more visible ( bold + 2px border ).
The whole is in testing.
