### ISSUE TITLE
List Management Module

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#191]
There are some minor issues with the listmanagement module.

First the birthday syntax check fails when der is a blank in this field. I suggest to ignore these. Second this fails when the birthdate is in the wrong format (eg. no leading zero).
Both of this is inconvenient when switching from lmn6 which contains both of this in a default lehrer.txt.

When adding a teacher the login field is optional. Its possible to auto generate teacher usernames when enabling min characters in import settings in the school.conf.
This also affects the list upload module.

**Comment by kiarn** [comment]
Hello @PLanB2008 

> First the birthday syntax check fails when der is a blank in this field. I suggest to ignore these. 

The birthday is not required anymore ? I thought it was a necessary input.

> Second this fails when the birthdate is in the wrong format (eg. no leading zero).

Ok, I will show at it. 

> When adding a teacher the login field is optional. Its possible to auto generate teacher usernames when enabling min characters in import settings in the school.conf.
> This also affects the list upload module.

So it's necessary to allow empty login field for the teachers.

**Comment by PLanB2008** [comment]
> The birthday is not required anymore ? I thought it was a necessary input.

I assume I wasn't clear in describing the issue. The field is still mandatory. The issue occurs when you have an additional (or more than one) blank character / whitespace in this field.

This happens when you take a look at a line of the old lmn 6 lehrer.txt:

```
lehrer ;Netzint       ;Support       ;01.01.1980 ;netzint  ;---  ;usertoken ;1500+1500 ;mailquota ;
lehrer ;Netzint2      ;Support2      ;01.01.1980 ;netzint2 ;---  ;usertoken ;quota     ;mailquota ;

```

Not sure which part of lmn tries to display the csv nice but it adds a lot of whitespace. I would suggest just to clean this in the webui.

When import such a file this works flawlessly until you try to edit a any field. This triggers the webui to validate all inputs and stops at this point.

I hope I could enlighten you a little  :)

**Comment by kiarn** [comment]
The last commit removes all leading and trailing spaces for all fields in all CSV ( devices, students, etc ... ).
It seems to work on my installation.
The birthdate problem is solved too.

Empty logins for teachers are already allowed : https://github.com/linuxmuster/linuxmuster-webui7/blob/7fa63acf2a07ad57c30b5047b73ef297370be2bc/usr/lib/linuxmuster-webui/plugins/lmn_users/resources/js/controllers/listmanagement.controller.coffee#L404

Maybe I didn't understand the third point too ?

**Comment by PLanB2008** [comment]
> The birthdate problem is solved too.
> 
> Empty logins for teachers are already allowed :
> 
> https://github.com/linuxmuster/linuxmuster-webui7/blob/7fa63acf2a07ad57c30b5047b73ef297370be2bc/usr/lib/linuxmuster-webui/plugins/lmn_users/resources/js/controllers/listmanagement.controller.coffee#L404

You're right, this seems to work. I have to look into this again. Maybe the patchlevel was to low on the last environment I checked. 

I'll close the issue. Thanks for your support!
