### ISSUE TITLE
Exception in latest testing

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#193]
Hi,

I just cloned and built the testing branch, and I get an exception over here:
https://github.com/linuxmuster/linuxmuster-webui7/blob/7828f69c296efcab2f69e5d36633a7ad3217b794/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py#L193

When opening the list management:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 207, in handle_api_students
    os.mknod(path)
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden
```

**Comment by dorianim** [comment]
It think the problem is that the global-admin is in the school `global`. This causes many more issues with other plugins as well.

**Comment by kiarn** [comment]
Hi,

The multischool is running pretty well, I'm using it on many servers. Can you please print the path to show what's is going on ?
What do you mean exactly with "built" ?

Arnaud

**Comment by dorianim** [comment]
Hi Arnaud,

How do I print the path?
I just cloned the repo and ran buildpackage.sh
Should I have done something elese?

**Comment by dorianim** [comment]
Ok, so it works with `global-admin` but not with global-admins who have a different username.

**Comment by kiarn** [comment]
Perfect. With this information I can reproduce and confirm it.
I made a quick fix.
@PLanB2008 is more implicated into multischool, so I let him have a look at this in order to confirm there's no side effects.

**Comment by dorianim** [comment]
Your fix works for me :+1:
