### ISSUE TITLE
Question about the customFields plugin

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#194]
Hi Arnaud,

First, thank you for your great work on the webUI! I just implemented the import of private email addresses through the new custom CSV upload, and it works perfectly :D This simplifies our workflow a lot.

I have a question about the customFields plugin:
I set CustomDisplay1 to sophomorixCustom1: 
![image](https://user-images.githubusercontent.com/30153207/135093003-5fb4d6fc-dc7b-42d5-bfc1-76b64727a9de.png)

And I can see and edit it in the user details:
![image](https://user-images.githubusercontent.com/30153207/135093242-2058e039-beab-4251-9029-2d604bbcb595.png)

But, the field is not visible in the list view, as [over here](https://github.com/linuxmuster/linuxmuster-webui7/issues/182#issuecomment-869142860):
![image](https://user-images.githubusercontent.com/30153207/135093494-2b48cafa-6596-4fea-b4c2-7f5ace042915.png)
(it is not caused by the user being in attic, it is the same for all users)

Furthermore, I noticed an empty bar at the bottom:
![image](https://user-images.githubusercontent.com/30153207/135093838-83b0b36e-40f2-4e0a-8a8d-5b0874b4c2cf.png)

Shouldn't there be some buttons?

Regards,
Dorian

**Comment by kiarn** [comment]
Hi Dorian,

Thanks for your positive feedback.
For the moment, I have only implemented this in the teacher view, not in the student view.
I wanted to wait a feedback from the other dev to know if we keep this or if it's unnecessary.
I think it's useful, in particularly when we want to handle all private emails or parents emails.
Implementing this for the student is not a big deal, I can do this this week.

Arnaud

**Comment by dorianim** [comment]
Ok, cool :+1:

**Comment by kiarn** [comment]
Done, but I need to ameliorate the design since I find the result pretty ugly :)

**Comment by kiarn** [comment]
The data are yet better displayed, just waiting to migrate to B4 in order to habe more design options.
