### ISSUE TITLE
Collapse not working for quota in user details

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#195]
Just a minor thing:
The collapse button is not working for Quota in the user details of a student:
![image](https://user-images.githubusercontent.com/30153207/135124331-be665fc8-8bd6-46c0-b038-467901cee4ea.png)
Clicking "Ausblenden" just changes the label:
![image](https://user-images.githubusercontent.com/30153207/135124437-7216317d-ce74-4b78-bdab-eaebe3c272de.png)
Same for teachers.

Regards,
Dorian

**Comment by kiarn** [comment]
Fixed.
