### ISSUE TITLE
Exception with empty custom fields

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#196]
Hi Arnaud,

I just tested your changes from #194, and it looks excellent, thank you very much :+1:
Just one minor problem: When there are some students who have an empty value in the custom field, an exception occurs:
![image](https://user-images.githubusercontent.com/30153207/135732803-fc8c25a9-1ba5-417e-a49d-e835ce8284cb.png)
![image](https://user-images.githubusercontent.com/30153207/135732811-8d6a3456-67c7-47fd-bc33-1c36d1f7333d.png)

Regards,
Dorian

**Comment by kiarn** [comment]
Hi,

Thanks for the report. I have a lot of students with empty values, I don't think this is the problem, but more the fact that not all 3 custom displays are configured, my bad.
I will have a look at this tomorrow, I currently work on linbo 4.

Arnaud

**Comment by kiarn** [comment]
Should be fixed.
