### ISSUE TITLE
Option to edit start scripts in sysvol

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#197]
Hi,

Just a little Idea I had:
It would be helpful to have an option to modify the scripts in `/var/lib/samba/sysvol/linuxmuster.lan/scripts/default-school/custom`.
This is not super important, though.

Dorian

**Comment by kiarn** [comment]
Hi,

I forgot to answer here, sorry for that.
Which scripts especially ? 

That's the tree I have : 

```$ tree /var/lib/samba/sysvol/lmn.lan/scripts/default-school
/var/lib/samba/sysvol/lmn.lan/scripts/default-school
├── custom
│   ├── linux
│   │   ├── logoff.sh
│   │   ├── logon.sh
│   │   ├── sysstart.sh
│   │   └── sysstop.sh
│   └── windows
│       ├── logoff.bat
│       ├── logon.bat
│       ├── sysstart.bat
│       └── sysstop.bat
├── linux
│   ├── login.script
│   ├── login.script.20190325151244
│   ├── login.script.20190325153317
│   ├── login.script.20190325170037
│   ├── login.script.20190325171606
│   ├── login.script.20190325172704
│   ├── login.script.20190325173908
│   ├── login.script.20190325202232
│   ├── login.script.20190325205742
│   ├── login.script.20190325210549
│   ├── login.script.20190405145017
│   ├── login.script.20190513120158
│   ├── login.script.20190520175610
│   ├── login.script.20200529183200
│   ├── login.script.20200529183357
│   ├── login.script.20200529183614
│   ├── login.script.20200529184109
│   ├── login.script.20200529184703
│   ├── login.script.20200529184914
│   ├── login.script.20200618223321
│   ├── login.script.20200721142235
│   ├── login.script.20200721150812
│   └── login.script.20210514110909
└── lmn
    ├── linux
    │   ├── logoff.sh
    │   ├── logon.sh
    │   ├── sysstart.sh
    │   └── sysstop.sh
    └── windows
        ├── logoff.bat
        ├── logon.bat
        ├── sysstart.bat
        └── sysstop.bat
```

Or do you mean all except the backups ( e.g. `login.script.*` ).

Arnaud

**Comment by dorianim** [comment]
Hi arnaud,

Just the ones in `/var/lib/samba/sysvol/lmn.lan/scripts/default-school/custom`.
The login.script* are obsolete and not used anymore in the wen client.

Regards,
Dorian

**Comment by kiarn** [comment]
Hi,

If I understand correctly, these scripts are provided through sophomorix, but I didn't find a documentaion on the wiki.
Only here : https://github.com/linuxmuster/linuxmuster-linuxclient7/wiki/Hook-scripts

Is it only used in linuxclient7 ?
I ask because I need to put it in the right place in the webui.

Arnaud

**Comment by dorianim** [comment]
HI Arnaud,

Yes, these scripts are created by sophomorix and there is no proper documentation on this.
They are used in the linuxclient (https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/19e41e02aae7409baec47a1a5f8a9caaae414ea8/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/hooks.py#L32) and slightly diffrently in the windowsclient (https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/config-devel/gpo/school/Machine/Scripts/scripts.ini and https://github.com/linuxmuster/sophomorix4/blob/bionic/sophomorix-samba/config-devel/gpo/school/User/Scripts/scripts.ini)

But sophomorix does not yet create the correct scripts (see https://github.com/linuxmuster/sophomorix4/issues/134), so you have to handle that in the webui.

I think the right place in the webui are the school settings.

**Comment by kiarn** [comment]
Hi Dorian,

I placed this in device management, I think it's better there.

Arnaud
