### ISSUE TITLE
Allow to create cron task which can be accessed by all admins

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#210]
Hi,

I really like the new cron plugin, I'm using it to execute regular syncs with linbo_remote.
But because the plugin uses my own crontab, other admins cannot see  and edit my tasks. Would it be possible to add an option to create a "global" cron task (maybe in root context) which every admin can edit?

Regards
Dorian

**Comment by kiarn** [comment]
Hi,

I was awaiting this request.
I see 2 solutions for this : 

- as admin, open a `crontab` as root, which can be shared over all admins, and can reuse the same backend
- edit `/etc/crontab` which is considered as bad practice ( what I always do ) and need some improvement on the backend.

The first solution seems better.

**Comment by dorianim** [comment]
I also prefer the first solution :+1:

**Comment by PLanB2008** [comment]
You could also add a checkbox like dorian suggested "global-crontab" and run crontab -u global-admin or something like that (specifying the user which is linked to the global cronjobs).
But this begs the question: Do we need user specified crontabs at all? I mean in a multischool environment it makes sense to have "global" cronjobs and school specific. Other than that I would not offer every user the option to run cronjobs for security reasons. 
What do you guys think?

**Comment by dorianim** [comment]
I don't think, we should use ssh. It is a pain to set it up under windows.

I would prefer something like this:
- we have an mqtt beoker in the server
- all clients run a daemon which connects to it
- they publish their details like os, version, logged in users, uptime, ...
- they subscribe to some some subject where the server publishes actions for them to execute, like shutdown, reboot, suspend, ...

Like this, we have bidirectional communication and are very flexible.
I would suggest using golang for the daemon, because it compiles to a static binary with no dependencies and can run on any platform (even android)
I would love this solution, but it would be some work to implement it, maybe as a new package linuxmuster-remote or something similar.

**Comment by kiarn** [comment]
The plugin is initially a copy of the ajenti plugin, with holiday addon, which currently does not work.
The actual permissions only allows global and school admins to change this, no one else.
I also think that only one cron would be enough in a single school env.
One more thing to discuss in a meeting ... we already have a lot for the next meeting, the biggest question will be to find a date for this.

**Comment by kiarn** [comment]
Hello,

Since I was working on it today to enable school specific holidays, I suggest the following : 

  * all global admins open the same cron file, the one from the user `global-admin`
  * school admins can all open the same cron file from the school they belong. It's easy to check the school, but we need a common user for all school admins from the same school and for this point I have no idea. Other solution : only `global-admins` can edit cronjobs.

Arnaud

**Comment by dorianim** [comment]
Sounds good to me :)

**Comment by kiarn** [comment]
Hello,

Do you mean that only `global-admins` can edit cron jobs ?

Arnaud

**Comment by dorianim** [comment]
Yes. In my opinion, this is fine, as it is a very low-level administrative task.
