### ISSUE TITLE
Obsolet parameter in webui.yml

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#211]
Hello,

Since I'm filling the documentation, I saw that the parameter `is-configured`, `provision` and `initialized` in `/etc/linuxmuster/webui.yml` are not used.

The setup wizard is triggered when the file `/var/lib/linuxmuster/setup.ini` does not exists, and I don't any use of these variables in the webui or in linumxuster-base, so I think it's obsolet and we can remove it.

But just before I do it, can you please confirm @PLanB2008 ?

Thanks

Arnaud

**Comment by PLanB2008** [comment]
Indeed these are not used. Maybe we **should** starting using them instead of relying on the existence of setup.ini?

**Comment by kiarn** [comment]
I remove this for the moment for a clean structure, but I keep in mind we can eventually use it in the future :+1:
