### ISSUE TITLE
WebUI does not respect comments in devices.csv

### ISSUE THREAD

**Issue by garblixa** [linuxmuster/linuxmuster-webui7#213]
Hello,

When devices.csv is edited directly and an entry exists like the following, webui then returns an error when saving and importing.
````
#raum01;raum01-client1;win10_sata_s;08:00:27:AB:E1:94;10.0.1.1;;;;classroom-studentcomputer;;1
raum01;raum01-client2;win10_sata_s;08:00:27:AB:E1:94;10.0.1.2;;;;classroom-studentcomputer;;1
````

Error:
````
08:00:27:AB:E1:94 ist ungültig oder doppelt vorhanden
````
WebUI should respect comments in devices.csv

Thanks
Klaus

**Comment by dorianim** [comment]
CSV does not support comments by default:
https://stackoverflow.com/questions/1961006/can-a-csv-file-have-a-comment

**Comment by garblixa** [comment]
> CSV does not support comments by default: https://stackoverflow.com/questions/1961006/can-a-csv-file-have-a-comment

Since WebUI already respects comments in other areas of devices.csv, this should also happen when comparing for duplicate host/IP/MAC entries.

**Comment by kiarn** [comment]
Yes, it's not a good practice to write comments in csv, but it was already implemented as I joined the team.
But my last test show that the commented line was not completely copied ( @garblixa : can you please confirm it ? ), so I fix it today.

Removing the commented lines from the validation was not a big deal, it's done : https://github.com/linuxmuster/linuxmuster-webui7/commit/101213fea83457be7940e7b81de2595c38d8eed8

Arnaud

**Comment by garblixa** [comment]
Hello Arnaud,

> Yes, it's not a good practice to write comments in csv, but it was already implemented as I joined the team.

To the general discussion if it is correct to use comments in .csv files I would like to say that I think it is correct and state of the art on unix systems to use comments in text files. Comments are used in any linuxmuster pattern configuration file. There is a WebUI for the devices.csv to add entries and a WebUI editor. Therefore the file could also be called devices.txt and external editing with a program that separates text using semicolons as separators need not be considered.

> But my last test show that the commented line was not completely copied ( @garblixa : can you please confirm it ? ), so I fix it today.

Yes, its true, if you have a comment that contains a semicolon, everything after the first semicolon is deleted when imported through the WebUI. So if the entries contains different MAC/IP/Hostname and not before the check for duplicate entries takes place. Can confirm.

Bevore:
````
#raum01;raum01-client1;win10_sata_s;08:00:27:AB:E1:95;10.0.1.1;;;;classroom-studentcomputer;;1
raum01;raum01-client2;win10_sata_s;08:00:27:AB:E1:94;10.0.1.2;;;;classroom-studentcomputer;;1
````
After:
````
#raum01
raum01;raum01-client2;win10_sata_s;08:00:27:AB:E1:94;10.0.1.2;;;;classroom-studentcomputer;;1
````

> Removing the commented lines from the validation was not a big deal, it's done : [101213f](https://github.com/linuxmuster/linuxmuster-webui7/commit/101213fea83457be7940e7b81de2595c38d8eed8)

Very nice, thank you for the quick turnaround and fixing!

Kind regards
Klaus

**Comment by kiarn** [comment]
Hello Klaus,

> Yes, its true, if you have a comment that contains a semicolon, everything after the first semicolon is deleted when imported through the WebUI. So if the entries contains different MAC/IP/Hostname and not before the check for duplicate entries takes place. Can confirm.

Ok, thanks, it's since yesterday already solved : https://github.com/linuxmuster/linuxmuster-webui7/commit/f79edbe28ed25dd79cdb1afe0fb7190bfe74b447, so I think I can close this.

Arnaud
