### ISSUE TITLE
webui accepts capital Letters in room and devicenames, linbo4 does not like them

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-webui7#214]
Hello there,

pleas regard this post in ask.linuxmuster.net
I think webui should not suggest A23 as a Room Name and it would be marcvolous if it could generate a Error stating capital Letters are not allowed in Room or Devicenames.

https://ask.linuxmuster.net/t/linuxmuster-net-7-1-testing/8265/33

Yours
Holger

**Comment by kiarn** [comment]
Hello Holger,

It doesn't seem to be related to the Webui, so I'm closing it for the moment.

Arnaud
