### ISSUE TITLE
Distribution of files failes after upgrade from stable version / missing script call in postinst

### ISSUE THREAD

**Issue by lemertens** [linuxmuster/linuxmuster-webui7#217]
After updating from 7.1.0 version the distribution of files does no longer work due to a permission error on folder /srv/webUiUpload.
This might be a result of a missing call of  /usr/lib/linuxmuster-webui/etc/create_webuiUploadFolder.sh  during post-installation, as the mentioned script does recreate the mentioned folder with correct permissions.

**Comment by PLanB2008** [comment]
Fixed in 77821de2feee31d2a2ba0dc55b026165dfa6837b
