### ISSUE TITLE
Holidays should be school specific

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#224]
At the moment the module uses /etc/linuxmuster/holidays.yml.

This does not work in a multischool environment, especially if these schools use different holidays. 

The module should save the holidays in different files like sophomorix. eg. kbrs.holidays.yml

In addition the linuxmuster-holiday script needs an argument to define which school is used.

**Comment by kiarn** [comment]
Hello,

I was awaiting this comment. That's why I think it's necessary that we talk about multischool.

Arnaud

**Comment by kiarn** [comment]
Hello,

Already done for the settings, but for the crontab plugin, I need to list all existing schools on the server.
Can you please confirm that I can achieve this with : 

```
sophomorix-school -ij
```

and then use `LISTS/SCHOOLS` ?
On my test server, there's more entries in `LISTS/SHARES` than in `LISTS/SCHOOLS`.

Arnaud

**Comment by kiarn** [comment]
This is quite done in crontab plugin, but I need to add a select for the global-admin, so that he can select the right school to apply the holidays. That's why I asked a few hours about listing the schools.

**Comment by dorianim** [comment]
This problem already existed a while back: https://github.com/linuxmuster/sophomorix4/issues/112

**Comment by kiarn** [comment]
I think it's ok how it actually works.
