### ISSUE TITLE
Move Custom Fields Tab to Global Settings

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#225]
Like Subnets settings this setting is used for every school in a multischool context. This needs to be moved to global-settings.

**Comment by kiarn** [comment]
Hello,

> This needs to be ...

Maybe we should discuss it first ;)

User management is school specific, so I don't get why custom fields could not be school specific too.
I wanted to split the config file anyway, and moving to globa settings would block school admins from editing this.

Arnaud
