### ISSUE TITLE
Deleting a linbo group (Hardwareklasse) doesn't delete the grub conf

### ISSUE THREAD

**Issue by michaelkohls** [linuxmuster/linuxmuster-webui7#227]
When deleting a linbo group (hardware class) in the webui, the associated start.conf.example in /srv/linbo is deleted, but not the associated grub.conf in /srv/linbo/boot/grub (example.conf). 
From my point of view, the grub conf should also be deleted in order to keep the system clear.

**Comment by kiarn** [comment]
Hello @michaelkohls 

Thanks, that's a good point, but you mean surely `/srv/linbo/boot/grub/example.cfg` and not `/srv/linbo/boot/grub/example.conf` ?

@dorianim : I don't see it as a bug, but more as enhancement.

Arnaud

**Comment by dorianim** [comment]
> I don't see it as a bug, but more as enhancement.

I don't mind changing the labels.

**Comment by kiarn** [comment]
@dorianim : do you know when a `grub.cfg` is created ?
I'm testing right now the following : 

- create `start.conf.mygroup`,
- use `mygroup` for a device,
- launch `linuxmuster-import-devices`.

But after this I don't see any `mygroup.cfg` in `/srv/linbo/boot/grub`.

**Comment by dorianim** [comment]
I think, it is created by linuxmuster-import-devices, but only when there is a device using it in devices.csv

**Comment by kiarn** [comment]
Ok thanks, I thought the same ( and I tried to say it with "use mygroup for a device" :) ), but it doesn't work on my test server. I must test further ...

**Comment by dorianim** [comment]
If it helps - its done over here:
https://github.com/linuxmuster/linuxmuster-base7/blob/a35a6d08a885c6aeb8c04be48f2c085239d282c1/sbin/linuxmuster-import-devices#L80

**Comment by michaelkohls** [comment]
Hello @kiarn 

> Thanks, that's a good point, but you mean surely `/srv/linbo/boot/grub/example.cfg` and not `/srv/linbo/boot/grub/example.conf` ?

You are right. I mean `/srv/linbo/boot/grub/example.cfg`.

Thanks
Michael

**Comment by kiarn** [comment]
> If it helps - its done over here: https://github.com/linuxmuster/linuxmuster-base7/blob/a35a6d08a885c6aeb8c04be48f2c085239d282c1/sbin/linuxmuster-import-devices#L80

Thanks, it was a misconfiguration on my instance.
File `example.cfg` will now be deleted too.

Arnaud

**Comment by michaelkohls** [comment]
@kiarn: Great, that was quick. 👍 Thanks!
