### ISSUE TITLE
Add plugin to edit GPOs

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#228]
Hi,

It would be nice to have a plugin which allows to edit the drives.xml (and maybe also printers.xml) gpos. Many users are having trouble configuring them, and this would be super helpful for them :)

Regards,
Dorian

**Comment by kiarn** [comment]
Hi,

Yes, I wanted this since the beginning. Is there a documentation of the possible options and syntax ?

Arnaud

**Comment by dorianim** [comment]
I found this:
- https://docs.microsoft.com/en-us/openspecs/windows_protocols/ms-gppref/1b0df77e-9f78-4be0-b55a-988ac916b425
- And this: https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn581924(v=ws.11)#xml-file-configuration

**Comment by dorianim** [comment]
Hi Arnaud,

If it helps: I created some example files for the unittests of the linuxclient:
https://github.com/linuxmuster/linuxmuster-linuxclient7/tree/feat/tests/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/tests/files

Policy1 is completely valid and the other ones have different flaws. The invalid ones should cover most edge-cases.

The corresponding unittest is this one:
https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/feat/tests/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/tests/test_gpo.py

And this is my cide for processing them:
https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/feat/tests/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/gpo.py

You may be able to copy pastes some parts :)

Regards,
Dorian

**Comment by PLanB2008** [comment]
Just a minor addition:

This is a GPP GroupPolicyPreference. GPOs are stored in a binary format.

**Comment by dorianim** [comment]
Oh, ok. Good to know. Where are they stored?

**Comment by Buster-de** [comment]
Location of GPP within GPO is documented at https://docs.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2012-r2-and-2012/dn581924(v=ws.11)

I want to raise awareness that Group Policy Management Console exists and can be installed on any modern Windows client as part of [Remote Server Administration Tools](https://docs.microsoft.com/en-us/windows-server/remote/remote-server-administration-tools) and/or Feature on Demand. Also Microsoft released its own web interface to manage Windows servers, called [Windows Admin Center](https://www.microsoft.com/en-us/windows-server/windows-admin-center).

**Comment by dorianim** [comment]
> I want to raise awareness that Group Policy Management Console exists and can be installed on any modern Windows client

I'm aware of that. The intention behind this issue is to create a simple and easy to use interface for the printer and drive GPPs to users don't have to go through the process of setting up any Microsoft stuff.

**Comment by PLanB2008** [comment]
> Also Microsoft released its own web interface to manage Windows servers, called [Windows Admin Center](https://www.microsoft.com/en-us/windows-server/windows-admin-center).

Is this compatible with samba 4 servers?

**Comment by PLanB2008** [comment]
> Oh, ok. Good to know. Where are they stored?

Oh I did not catch this one, they are both stored along the gpps in sysvol/$DOMAIN/Polices/$GPO/Machine/ as Registry.pol

**Comment by kiarn** [comment]
Hello,

I've prepared a minimalistic tab to modify `useLetter`, `letter` and `disabled` in `Drives.xml`.
Available letters in the select are only the one not used.

![20220803-125037](https://user-images.githubusercontent.com/10401079/182591299-ba9c936a-abf3-454e-875e-ccb9f905043b.png)

It will not be published for now, because I'm waiting that `sophomorix-school --gpo-listall -jj` gives an output in the right json format.

Arnaud

**Comment by dorianim** [comment]
Looks really promising!
