### ISSUE TITLE
Setup does not save date when going back

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#23]
The data a user enters during setup is not stored when you go back:

![peek 2018-05-21 19-19](https://user-images.githubusercontent.com/708888/40307278-005f4ea2-5d2c-11e8-92ed-54ec8799ef6e.gif)

**Comment by PLanB2008** [comment]
fixed in 078477c23cb6a3da73cddbe93f4538da648dbccf
