### ISSUE TITLE
lmn_settings permission needed for teachers

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#232]
https://github.com/linuxmuster/linuxmuster-webui7/blob/451cfa86aa8cb21b4deb0e10d9ea93f2ef4bce87/usr/lib/linuxmuster-webui/plugins/lmn_settings/permissions.yml#L10

This seems to throw an error when opening user information as a teacher.

![grafik](https://user-images.githubusercontent.com/26460239/165134041-7b8c091c-3387-4f63-bab5-d886e57ff13a.png)

**Comment by kiarn** [comment]
~~A teacher should not be able to open user details, only admins.~~
But I just saw that the teacher have access to students details in the session module, I was not aware of this.
I will have a look at this.

**Comment by PLanB2008** [comment]
Not sure if this shouldn't be possible. I see the need for a teacher looking for groups or quota of a student.

**Comment by kiarn** [comment]
I forgot to strike the first sentence ;)

**Comment by kiarn** [comment]
The only decision to take is : should a teacher see the content of the custom fields ?
The simpliest solution would be to display custom fields only for admin roles in the user details.

**Comment by PLanB2008** [comment]
It depends... I havent had confidential information in mind when we were talking about this custom fields but I could see some user wanting this feature...

My personal opinion: Let them see everything but if you would like to hide it - go for it :)
