### ISSUE TITLE
samba home plugin exception

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#235]
Hi Arnaud,

I tried out the new home plugin, but unfortunately, I get an empty list when opening it. When trying to create a folder, I get this exception:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/smbprotocol/session.py", line 278, in connect
    out_token = context.step(in_token)
  File "/usr/local/lib/python3.6/dist-packages/spnego/_negotiate.py", line 124, in step
    mech_token_in, mech_list_mic, is_spnego = self._step_spnego_input(in_token=in_token)
  File "/usr/local/lib/python3.6/dist-packages/spnego/_negotiate.py", line 171, in _step_spnego_input
    mech_list = self._rebuild_context_list(mech_types=in_token.mech_types)
  File "/usr/local/lib/python3.6/dist-packages/spnego/_negotiate.py", line 416, in _rebuild_context_list
    raise BadMechanismError(context_msg="Unable to negotiate common mechanism", base_error=last_err)
spnego.exceptions.BadMechanismError: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/aj/api/endpoint.py", line 75, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_smbclient/views.py", line 210, in handle_api_smb_create_directory
    smbclient.makedirs(path)
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_os.py", line 288, in makedirs
    mkdir(mkdir_path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_os.py", line 267, in mkdir
    raw = SMBDirectoryIO(path, mode='x', **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_io.py", line 377, in __init__
    tree, fd_path = get_smb_tree(path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_pool.py", line 312, in get_smb_tree
    auth_protocol=auth_protocol)
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_pool.py", line 383, in register_session
    session.connect()
  File "/usr/local/lib/python3.6/dist-packages/smbprotocol/session.py", line 280, in connect
    raise SMBAuthenticationError("Failed to authenticate with server: %s" % str(err.message))
smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism
```

Regards,
Dorian

**Comment by kiarn** [comment]
Hi,

Kerberos auth didn't worked. Is there a file `/tmp/krb5cc_USERID` on the server ? 
You can check it with `klist /tmp/krb5cc_USERID`, but I'm pretty sure you have known it already.

Other possibility : the library `smbprotocol` is not installed with kerberos support, this can happen if there's an incompatibility with `gssapi` : https://github.com/jborean93/smbprotocol#requirements

Cheers

Arnaud

**Comment by dorianim** [comment]
The kerberos ticket exists:
![image](https://user-images.githubusercontent.com/30153207/169712677-24e11f09-a309-480b-9cd1-00328a05cd76.png)

And it also seems that smbprotocol is installed:
![image](https://user-images.githubusercontent.com/30153207/169712706-20ea92ed-1d23-4e28-92f3-afbfccf87d3c.png)

Anything else I can test?

Regards,
Dorian

**Comment by kiarn** [comment]
Yes : 

```python
try:
    from gssapi.raw import inquire_sec_context_by_oid
    print("python-gssapi extension is available")
except ImportError as exc:
    print("python-gssapi extension is not available: %s" % str(exc))
```

**Comment by dorianim** [comment]
Seems to work:
![image](https://user-images.githubusercontent.com/30153207/169712825-5ec61c09-d56d-4f8c-adcb-db5535be4655.png)

**Comment by kiarn** [comment]
Are `python-dev, libkrb5-dev, gcc` installed on your system ?
Can you eventually try to install `smbprotocol` yourself to see what happen ?

```
pip3 uninstall -y smbprotocol
pip3 install smbprotocol[kerberos]
``` 

Maybe we can see some error.

Arnaud

**Comment by dorianim** [comment]
![image](https://user-images.githubusercontent.com/30153207/169713740-fb62da58-06b2-4296-ab45-fcd3573f58d2.png)
Unfortunately, there does not seem to be a problem with the packages.

**Comment by kiarn** [comment]
I don't get the problem. Please try this (variable home must have the right realm, and the kerberos must still be present in `/tmp`):

```python
$ python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smbclient, os
>>> os.setgid(100)
>>> os.setuid(3000072)
>>> home = '\\\\REALM\\default-school\\ROLE\\default-testnutzer' 
>>> for obj in smbclient.scandir(home):
...     print(obj)
``` 

Based on the uid from the process, `smbprotocol` try to find a ticket in `/tmp/krb5cc_UID` and use it, that's why it's necessary to make a setuid.
Or is it a special account not listed in sophomorix roles ?

Arnaud

**Comment by dorianim** [comment]
>  Or is it a special account not listed in sophomorix roles ?

It's an extra-student in the default-school:
`test;Test;Nutzer;01.01.2000;default-testnutzer;`
(I also tested with a normal student, does not seem to make a difference)

When executing the commands you sent, I get a similar error message:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/smbprotocol/session.py", line 278, in connect
    out_token = context.step(in_token)
  File "/usr/local/lib/python3.6/dist-packages/spnego/_negotiate.py", line 124, in step
    mech_token_in, mech_list_mic, is_spnego = self._step_spnego_input(in_token=in_token)
  File "/usr/local/lib/python3.6/dist-packages/spnego/_negotiate.py", line 171, in _step_spnego_input
    mech_list = self._rebuild_context_list(mech_types=in_token.mech_types)
  File "/usr/local/lib/python3.6/dist-packages/spnego/_negotiate.py", line 416, in _rebuild_context_list
    raise BadMechanismError(context_msg="Unable to negotiate common mechanism", base_error=last_err)
spnego.exceptions.BadMechanismError: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_os.py", line 526, in scandir
    with SMBDirectoryIO(path, share_access='rwd', **kwargs) as fd:
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_io.py", line 377, in __init__
    tree, fd_path = get_smb_tree(path, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_pool.py", line 312, in get_smb_tree
    auth_protocol=auth_protocol)
  File "/usr/local/lib/python3.6/dist-packages/smbclient/_pool.py", line 383, in register_session
    session.connect()
  File "/usr/local/lib/python3.6/dist-packages/smbprotocol/session.py", line 280, in connect
    raise SMBAuthenticationError("Failed to authenticate with server: %s" % str(err.message))
smbprotocol.exceptions.SMBAuthenticationError: Failed to authenticate with server: SpnegoError (1): SpnegoError (16): Operation not supported or available, Context: Retrieving NTLM store without NTLM_USER_FILE set to a filepath, Context: Unable to negotiate common mechanism
```

**Comment by kiarn** [comment]
I didn't find a explanation yet. Do you have this behaviour on both your test and production server ?
Does a request with the regular smbclient throw any error ?

**Comment by dorianim** [comment]
> Do you have this behaviour on both your test and production server ?

I only have the new WebUI installed on my test system, because we are still using linbo 2 in production.

>  Does a request with the regular smbclient throw any error ?

Works fine with password, but I don't know how to use it with a specific kerberos file.
Not sure, if this should work:
![image](https://user-images.githubusercontent.com/30153207/169874596-666edbe6-84ac-4700-8cb6-d396c0e938de.png)

**Comment by kiarn** [comment]
Hello,

If you have a domain, please try with the domain instead of the realm, it can be a DNS problem : 

```python
$ python3
Python 3.6.9 (default, Mar 15 2022, 13:55:28) 
[GCC 8.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import smbclient, os
>>> os.setgid(100)
>>> os.setuid(3000072)
>>> home = '\\\\DOMAIN\\default-school\\ROLE\\default-testnutzer' 
>>> for obj in smbclient.scandir(home):
...     print(obj)
```

In order to test with `smbclient`, you can do it this way : 

```bash
kinit -c /tmp/krb5cc_$(id -u USER) USER
chown USER:users /tmp/krb5cc_$(id -u USER)
smbclient -d 3 -U USER \\\\DOMAIN\\default-school -k
```

Then you should get a smb console to do `ls` or other stuff.

Cheers 

Arnaud

**Comment by dorianim** [comment]
It's really strange:
![image](https://user-images.githubusercontent.com/30153207/170045064-2bb1d96f-b7ec-4113-abf7-9d1ce1c5eff9.png)
For some reason, it says "ticket expired". This behaves the same on my testing and production system.

**Comment by kiarn** [comment]
Did you check it with `klist` ? Did you rolled back a snapshot and forgot to set the time ? ( happens to me all the time )

**Comment by dorianim** [comment]
The date is correct, but it created the ticket with a wrong expiry date:
![image](https://user-images.githubusercontent.com/30153207/170046942-d40c2a7e-4c48-4494-8860-297546c9b944.png)

**Comment by kiarn** [comment]
Sorry, but I don't see what's wrong with the expiry date.

**Comment by dorianim** [comment]
Yes, you're right, its fine

**Comment by kiarn** [comment]
My bad : calling `smbclient` as root is the problem. `smbclient` try to use the credentials cache located at `/tmp/krb5cc_0`, and this ticket is maybe expired. 
`kinit default-testbenutzer` let you define a ticket for root as default-testbenutzer.

**Comment by dorianim** [comment]
Yep, like this, it works on both systems

**Comment by kiarn** [comment]
So, I encounter the error mentioned in the first post if : 

 * the owner of the credentials cache is not set properly, here  `REALM\default-testbenutzer:users`
 * the ticket is missing or expired, here  `/tmp/krb5cc_3000072`
 * there is a problem with DNS

Did you try the Python code with domain instead of realm ?

**Comment by dorianim** [comment]
With the correct permission set, This worked too now (`$USER` is set to testnutzer):
`sudo -u LINUXMUSTER\\$USER smbclient -d 3 -U $USER \\\\server.linuxmuster.lan\\default-school -k`

But I still can't get it to work in python:
![image](https://user-images.githubusercontent.com/30153207/170114020-4d7d2757-ef0e-4174-be2c-2702f960ebf9.png)
neither with the whole domainname:
![image](https://user-images.githubusercontent.com/30153207/170114113-3d75f068-f073-4515-b2d8-b7ef4e734a76.png)
