### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by aloisr** [linuxmuster/linuxmuster-webui7#239]
Hello developers,

I have here:

https://ask.linuxmuster.net/t/lmn-7-x-was-loggt-ihr/9023/9

because of the logging. There came out a possible solution for logging. Is it possible to implement this in LMN?

Many greetings

Alois

**Comment by kiarn** [comment]
Hello @aloisr,

This is not only related to the Webui, I have already provided a full answer on the forum.

Arnaud
