### ISSUE TITLE
Students List should show the user name

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#24]
IMHO the students list should have a column "user name".

**Comment by jeffbeck** [comment]
Are you talking about the 36 Latex entries per page List?

datalist-DE-36-template.tex

??

**Comment by zefanja** [comment]
No, I'm talking about the students list view in the webUI7. It shows the fields from the CSV, but it would be helpful to show the user name, too.

**Comment by jeffbeck** [comment]
OK. I didn't notice that this issue is in the webui7 repo

**Comment by ni-kw** [comment]
The Students Plugin is only an editor with import function. So the Username should not really be shown. In the teachers list the username is part of the list itselve - so there it is shown.

**Comment by zefanja** [comment]
@ni-kw I know, but it would be nice if a teacher / admin opens the student list, he/she will get all the information + actions that are needed.

It would be nice to have just one list with all the details, where you can manage everything related, like setting a new password. Then there won't be a need for and extra Menu item "Passwords". Same for teachers.

**Comment by jeffbeck** [comment]
Are we talking about students.csv and teachers.csv and their display in Schulkonsole editor?

These a files to be **synced** in the database (Active directory)

That means, the Fields in these files are **updated** in AD, when they change in the files.

So I'm very reluctant to add passwords to these files, because these would be only used on user creation, and not synced.

see also 

man teachers.csv
man students.csv

**Comment by zefanja** [comment]
@jeffbeck I'm just talking from a user point of view. The school console needs to take care of the things you've described.

**Comment by ni-kw** [comment]
@zefanja I also think it would be nice to have less Plugins (menus) to do some jobs. But the Students list (students.csv) is only a file to import. I don't think that it is a good idea to merge a import list with a user-database (AD). The file could be complete different to the user databese. Users in the list may doesn't even have a passoword could be changed.

But we also don't like the seperate Modul for changing a password. So we try to give the teacher all the functions in the session plugin. The teacher can find users and there complete informations and can change the password.

**Comment by PLanB2008** [comment]
We tried to address this issue by separating the List Management (which is mostly just used twice a year) from the User Management.
In addition we'll add functionality to the session module so teacher will have the ability to do most of their administrative tasks from the session module.

![screenshot 20180607 17-41-27](https://user-images.githubusercontent.com/26460239/41110597-1a127468-6a7a-11e8-98eb-21b7c650e8e1.png)

Unfortunately this adds some clutter to the global-admin Sidebar.

![screenshot 20180607 17-42-34](https://user-images.githubusercontent.com/26460239/41110652-3533972c-6a7a-11e8-8b01-d1bd9899f3c8.png)

**Comment by PLanB2008** [comment]
I'm going to close this issue because session module and user management modules both show the username.
