### ISSUE TITLE
Hardware group not shown when base image names missing

### ISSUE THREAD

**Issue by thoschi** [linuxmuster/linuxmuster-webui7#241]
After creating a new hardware group and partitioning for this group, the group vanishes from the list of hardware groups in the Linbo section.
If I manually add base image names, the group comes back.
As mentioned in https://github.com/linuxmuster/linuxmuster-webui/issues/3 there should be a way to either set a name (even if there is no image present so far) or may allow a placeholder (like #tbc).

At least WebUI should show that this group is present (even if maybe "incomplete").

(this happened when creating a sata disk with 3 primary partitions (win+lin1+lin2) and an extended partition (linbo+data)).

**Comment by kiarn** [comment]
Hello @thoschi 

Fixed. I was not aware of the issues in the other deprecated repository.

Arnaud
