### ISSUE TITLE
UserID is not shown in user details

### ISSUE THREAD

**Issue by thoschi** [linuxmuster/linuxmuster-webui7#243]
After creating users including an ID (Hera ID in our case) when I open the details of a user, this ID is not shown (it shows Null instead).

Checking the user from CLI shows, that the ID has been added, so the import seems to work fine.

**Comment by kiarn** [comment]
Hello @thoschi 

Can you please provide a example line from users file ? I don't use ID and don't know where the ID are stored.
Which command do you use exactly to check this with CLI ?

I will have a look at this when I'm back.

Arnaud

**Comment by thoschi** [comment]
Hello @kiarn,

calling `sophomorix-user -i -u <uid>` i get the Unix ID: `sophomorixUnid: <unxi-id>`
The webui user details correctly labels "Hera-ID" (instead of custom) but shows "null" as a value here.

Does this help?

Thomas

**Comment by kiarn** [comment]
Hello @thoschi 

Thanks,
Can you please provide a line example from `teachers.csv` with fake names and ID so I can see in which column the Hera ID is written ?

Arnaud

**Comment by thoschi** [comment]
Hello @kiarn
Actually this problem is not (yet) with teachers but students. So a typical line would be 
`5a;Mayer;Inge;11.12.2013;12345`
The last column is the id and gets imported from sophomorix as `sophomorixUnid`.

Some (anonymized) sophomorix-log-line, just in case:

```
2022-xx-xx_xx-xx-xx.sophomorix.add-after:students.csv::5a::Mayer;Inge;11.12.2013::mayerin::---::---::---::12345::default-school::student::Mayer::Inge::U::---::---::---::---::---::mayerin@corvinianum.de::sidebar:view:/view/dashboard: false,sidebar:view:/view/lmn/home: true,sidebar:view:/view/lmn/landingpage: true,sidebar:view:/view/lmn/links: false,sidebar:view:/view/lmn/nextcloud: false,sidebar:view:/view/lmn/websession: false::sidebar:view:/view/dashboard: false,sidebar:view:/view/lmn/home: true,sidebar:view:/view/lmn/landingpage: true,sidebar:view:/view/lmn/links: false,sidebar:view:/view/lmn/nextcloud: false,sidebar:view:/view/lmn/websession: false::

2022-08-18_13-43-23.sophomorix.add-before:students.csv::5a::Mayer;Inge;11.12.2013::mayerin::---::---::---::12345::default-school::student::Mayer::Inge::U::---::---::---::---::---::mayerin@corvinianum.de::sidebar:view:/view/dashboard: false,sidebar:view:/view/lmn/home: true,sidebar:view:/view/lmn/landingpage: true,sidebar:view:/view/lmn/links: false,sidebar:view:/view/lmn/nextcloud: false,sidebar:view:/view/lmn/websession: false::sidebar:view:/view/dashboard: false,sidebar:view:/view/lmn/home: true,sidebar:view:/view/lmn/landingpage: true,sidebar:view:/view/lmn/links: false,sidebar:view:/view/lmn/nextcloud: false,sidebar:view:/view/lmn/websession: false::

```
Hope this helps!
Best regards
Thomas

**Comment by kiarn** [comment]
Hello @thoschi,

I don't succeed to reproduce it : 

```
10a test;Fraye;Katrin;11.05.1986;12345
10a test;Genglere;Felix;07.07.1985;3456
10a test;Ilkese;Judith;28.04.1985;654654
...
```

![20220829-190858](https://user-images.githubusercontent.com/10401079/187256240-80d88e87-9ad5-4485-87ce-65ed61be4d3d.png)

Students are imported and I can check it : 

```
$ sophomorix-user -u frayka -ivvv | grep Unid       
147:                sophomorixUnid: 4587
```

Even if I edit manually `students.csv`, I get the ID in the Webui.

The Unid is not part of the user details window, so I don't quite understand where you see a null for the Id.

Arnaud

**Comment by thoschi** [comment]
I think we are talking about different places. In the list management I see the IDs. But at the `users/students`-view I can open a details modal with the Null field although the student has a valid ID within sophomorix and in the students list:

![userdetail](https://user-images.githubusercontent.com/40145888/187265160-e82333b6-1cd6-48f8-ac8c-d786af0ae13a.png)

Best regards
Thomas

**Comment by kiarn** [comment]
Ok, I think you misunderstood the use of custom fields. 
You can only display fields like `sophomorixCustom**` in the user details and nothing else.
The custom fields feature is only for optional fields which can be editable, and not for fields like `sophomorixUnid`.
But I can also add the `Unid` in the user details, it's not a big deal.

Arnaud

**Comment by thoschi** [comment]
Hello Arnaud

you are right - so there is no connection between the possibility to import the ID (as a separate column) and the custom fields. I somehow connected that (probably missing the ID in the teachers list and using a custom field there). Sorry for mixing it up.

It would be great to see the student ID somewhere within the user details then.

Thank you
Thomas
