### ISSUE TITLE
FR: Load shares in home plugin from GPO

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#247]
Hi Arnaud,

I think, it would be nice if the shares over here
![image](https://user-images.githubusercontent.com/30153207/187218404-b96399a2-90f7-4c1e-a746-d7ee21664310.png)
in the home plugin were loaded from the GPO. Like this, the user has the same shares as on the clients.
The code for this could be reused for https://github.com/linuxmuster/linuxmuster-webui7/issues/228  :)

**Comment by kiarn** [comment]
Hi Dorian,

Yes, actually a good idea to ameliorate the integration.

> The code for this could be reused for #228 :)

The code in #228 is already done but not published, I don't get what you mean.

Arnaud

**Comment by dorianim** [comment]
> I don't get what you mean.

I just meant, that the code for parsing the GPO could be reused

**Comment by kiarn** [comment]
Unfortunately it is not that simple, because the normal user do not have permissions to read `Drives.xml`, and the UID of the Webui is in this case restricted.
This FR needs a complete code refactor.

How does it work in multischool environment ? Are there differents `Drives.xml` in use ?
@PLanB2008 @hermanntoast  : can you please tell us ?

Arnaud

**Comment by dorianim** [comment]
> Are there differents Drives.xml in use

Yes! The Drives.xml is determined by the GPO and the GPO is different for every school.

**Comment by dorianim** [comment]
You can see how I load it in the linuxclient here: 

https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/3d7cb5fbefc06603febbd3fb17773e03a1385fda/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/gpo.py#L47

Maybe, the user needs to mount the sysvol using samba. Then they should be able to access the drives.xml file.

**Comment by kiarn** [comment]
Ok thanks.
Doing a ldap search could be a good solution, because `sophomorix-school --gpo-listall` needs at least 3s on my system, and I can not imagine adding this to each login.

**Comment by dorianim** [comment]
Yes! Basically what you do is this:
1. construct the poicy name, it is `sophomorix:school:{school}`
2. find the poliy in LDAP: `(displayName={name from 1})`
3. get the policy path from the `gPCFileSysPath` attribute
4. load the policy from `{path from 3.}/User/Preferences/Drives/Drives.xml`

**Comment by kiarn** [comment]
Thanks, but in this case, that was already clear for me :D 
I've already tested as post the link to your code ;)
I will see if I can implement this in a quick way.
