### ISSUE TITLE
FR: sort IP-Addresses non-alphanumerical

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#249]
Hi,

IP-Addresses are currently sorted alphanumerial. I think, it would make more sense, to sort them like this:
```js
const ips = ['10.0.0.3', '10.0.0.11', '10.0.0.1']

let padIp = ip => ip.split(".").map(num => num.padStart(3, '0')).join(".")
ips.sort((a, b) => padIp(a) > padIp(b))

console.log(ips)
```

Currently, `10.0.0.11` is considered smaller than `10.0.0.2`, the above snippet fixes that. There might be a nicer way to implement this, though.

**Comment by kiarn** [comment]
Hello @dorianim 

Thanks, it's a good idea ;)

Arnaud
