### ISSUE TITLE
removing linuxmuster-webui7 will also remove linuxmuster-base7 and linuxmuster-linbo7

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#25]
If you want to remove `linuxmuster-webui7` it will also remove other important packages:

```
$ apt remove linuxmuster-webui7
...
Die folgenden Pakete werden ENTFERNT:
  linuxmuster-base7 linuxmuster-linbo7 linuxmuster-webui7
```

**Comment by netzint** [comment]
This pakage is in depency of linuxmuster-base7. It is an integral part of the solution and therefore ok
