### ISSUE TITLE
Problems, if classname = name of pupil

### ISSUE THREAD

**Issue by cgsman** [linuxmuster/linuxmuster-webui7#257]
Hello,
this is perhaps more a thing for sophomorix: If a user creates a new entry for a pupil  with the same name as a name for a class, there is a problem, because the result is a strange behaviour, see: https://ask.linuxmuster.net/t/klassenname-schuelername-in-extra-schueler/9867 .
Is it possible to check the values before ?
best regards
Christoph G.

**Comment by kiarn** [comment]
Thanks, it's more for sophomorix. I've copied your issue in the repository of sophomorix : https://github.com/linuxmuster/sophomorix4/issues/166

Arnaud
