### ISSUE TITLE
Improvements cron plugin

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#262]
Using the cron plugin should be improved.

There are 2 main improvements we should tackle:

- holiday.yml is not always readable by the global-admin / school admin.
- linuxmuster / sophomorix commands need to be run via sudo

For a user its not easy to understand why a cronjob is not running like intended. 

I think first of all the webui should create the holiday.yml with read access for all admins. The second issue is not as straight forward, but I think we could improve this.

**Comment by kiarn** [comment]
There's now the possibility to switch from globaladministrator to root when editing crontab.
