### ISSUE TITLE
Show extra shares in user files

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#265]
Hi Arnaud,

I have a share with the name `Labs` configured in the `Drives.xml` GPP. It does not show up in the user files at the moment, but it would be nice if that would be possible :)

This is the part from `Drives.xml`:
```xml
<Drive clsid="{935D1B74-9CB8-4e3c-9914-7DD559B7A417}" name="L:" status="L:" image="2" changed="2021-07-06 16:02:40" uid="{4E139383-A506-44C3-881B-79EFD9EA6343}" bypassErrors="1" disabled="0">
    <Properties action="U" thisDrive="SHOW" allDrives="NOCHANGE" userName="" path="\\server\default-school\share\projects" label="Labs" persistent="0" useLetter="1" letter="L" />
    <Filters />
</Drive>
```

Regards,
Dorian

**Comment by kiarn** [comment]
Hi Dorian,

It's quite an interesting feature what I totally support.

Actually, the shares are badly hard-coded : https://github.com/linuxmuster/linuxmuster-webui7/blob/02f471e34c9f07c55e5e065c8f79372280d6d2f7/usr/lib/linuxmuster-webui/plugins/lmn_common/multischool.py#L224

Beside the problem of getting the right path in a multischool environment, the main reason is that I cannot know in which roles another share should be shown. Do we have a way to configure this already ?

Arnaud

**Comment by dorianim** [comment]
Hi Arnaud,

The path should not be an issue. It is absolute and contains the school, since each school has their own policy.
For knowing which roles a share should be shown to, you need to parse the Filters object inside the share, see here for example:

https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/cf60b9570a684ae065a2e732a0ea8e1c488e02cb/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/tests/files/policy1/User/Preferences/Drives/Drives.xml#L10

This is the file I run the linuxclient unit tests on.

In the linuxclient, this is how I parse the filters:

https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/cf60b9570a684ae065a2e732a0ea8e1c488e02cb/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/gpo.py#L130

This is how I validate them:

https://github.com/linuxmuster/linuxmuster-linuxclient7/blob/cf60b9570a684ae065a2e732a0ea8e1c488e02cb/usr/lib/python3/dist-packages/linuxmusterLinuxclient7/gpo.py#L147

This code works fine in a multischool environment. 
Maybe, we should put all of this into the linuxmuster-tools and make the client depend on them. Like that, we could avoid having this code in two places.
What do you think?

**Comment by kiarn** [comment]
Hi Dorian,

Thanks for the examples! I don't think parsing is a problem. 
But we need a "line of conduct" to read the filters. I mean: if there's no filter, should we show the share to all roles, or to no one ?

> This code works fine in a multischool environment.

From the server point fo view, I first need to check if the share is bound with DFS. It should not be a big deal.

> Maybe, we should put all of this into the linuxmuster-tools and make the client depend on them. Like that, we could avoid having this code in two places.

Unfortunately, lmntools is only intended to work on the server, not from a client.

I will try to make some tests next week.

Arnaud

**Comment by dorianim** [comment]
Hi Arnaud,

>  But we need a "line of conduct" to read the filters. I mean: if there's no filter, should we show the share to all roles, or to no one ?

- If there are no filters, the share is shown to everyone.
- Filters we don't understand are treated like they are false

This is how I do it in the client.

> Unfortunately, lmntools is only intended to work on the server, not from a client.

ok.

**Comment by kiarn** [comment]
Hi Dorian,

I changed the title, because I think we are talking about <s>extra shares</s>. I must definitely use GPO/Filter to display the shares, that's the main point, it was already since ... long on my todo list, thanks for pointing it.

If i'm not wrong, you are not parsing the `not` attribute, but it could ne necessary to exclude roles.
I mean, a filter like `bool="AND" not"1" name="...\students"` would be interpreted as "all roles but not the students", don't you think ?

In a less relevant level, I will not be able to provide an icon for these extra shares, or do you eventually know if there's a free attribute for this ?

Arnaud

**Comment by dorianim** [comment]
> If i'm not wrong, you are not parsing the not attribute

Oh, you're right! I didn't know about the not attribute.

> In a less relevant level, I will not be able to provide an icon for these extra shares, or do you eventually know if there's a free attribute for this ?

I don't think, the gpo offers any option for an icon. And I don't think it would be a good idea to just add one. Maybe Windows will not like that and it will stop working...
