### ISSUE TITLE
FR: Duplicate images from Webui

### ISSUE THREAD

**Issue by dorianim** [linuxmuster/linuxmuster-webui7#266]
Hi @kiarn ,

I think it would be nice if it was possible to duplicate a linbo image in the webui. What do you think?

Regards,
Dorian

**Comment by kiarn** [comment]
Hi @dorianim ,

Yes, it's necessary, I wanted to do that anyway.
In my opinion, duplicating an image should only copy the orginal files (qcow2, qdiff, extras) and not the backups.
It's too risky to launch a copy with all backups and eventually completely fill the disk.

Is this behaviour ok for you ?

Arnaud

**Comment by dorianim** [comment]
Hi Arnaud,

> Is this behaviour ok for you ?

Absolutely! Copying all Backups could also take a lot of time.

**Comment by kiarn** [comment]
Done, I forgot to mention it in the commit message.
