### ISSUE TITLE
No Scrollbar at 2fa/totp section (/view/totp)

### ISSUE THREAD

**Issue by All0ne** [linuxmuster/linuxmuster-webui7#269]
Hello everyone,
first of all, thank you very much for your commitment :)

Small thing: in the area for adding the 2fa, the window with the QR code is displayed so large that the menu for saving/canceling is no longer visualized and the user is trapped in this menu. There is no scroll bar. You can only operate the whole thing using the browser's zoom function.

Kind regards

![webgui-2fa](https://github.com/linuxmuster/linuxmuster-webui7/assets/53848749/9975cdc4-64f4-4ba5-91c4-41749d6f9102)

**Comment by kiarn** [comment]
Hello @All0ne,

Thanks for the report, it's now fixed in Ajenti : https://github.com/ajenti/ajenti/commit/74cb8ec75e30cf0d53df4b2c88bf31034b071036

Regards,

Arnaud
