### ISSUE TITLE
Umlaute in project names

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-webui7#272]
Dear all, 

I would like to have german Umlaute "äöü" and "ß" in project names. 

The reason is, that while class names are usually made up of numbers with additional letters, project names could be anything. In my case, I usually have the shorthand notation of a teacher in the name of the project to identify the projects easily:
p_8a1_Kül vs. p_8a2_Mü

sophomorix_project allows these characters und programmatically these projects are already created like this.

However, webui only shows the projects, I am not able to call the modal dialog.

I know, this widens the character set basically to "unicode" and makes it more difficult. I hope there is an easy solution.

Tobias

**Comment by jolly-jump** [comment]
There is not even an error in the browser console. 
The red error modal dialog says: "Eigenschaften dieses Projekts können nicht gelesen werden"

**Comment by kiarn** [comment]
Hi @jolly-jump 

Can you please try to patch your Webui with the changes in https://github.com/linuxmuster/linuxmuster-webui7/commit/ab244d4bfe96b4f66d6b03719e79dc073b747ef1 and tell me if it's ok ? 

If yes, I must patch all other actions (delete, add members, etc ... )

Arnaud

**Comment by jolly-jump** [comment]
Yes, Arnaud. Thanks a million times. 
Quickest answer & fix ...

**Comment by jolly-jump** [comment]
Hi Arnaud,
the update came through and works using 

│ ii     │ linuxmuster-webui7             │ 7.2.56   │

what I wonder is, if the course-creation... (deutsch: Kurs -> Dieser Raum / Meine Klassen / Meine Gruppen / Meine Projekte)
is supposed to show projects with special characters.

Well: I have - at least - one with an umlaut. But there are no other (automatically created) courses from all the projects with the umlauts in the name.

:shrug:

**Comment by kiarn** [comment]
Hi @jolly-jump,

Thanks for the feedback, I didn't test this point, I will have a look at it.
Did I unterstand it correctly: only one projects with special chars shows up in the session module, but not the others ? 
Do the other projects have some attributes like hidden or only for admin ?
A project will only appear in the session module if the teacher is owner or admin of the project (I must verify this point).

**Comment by kiarn** [comment]
Hi @jolly-jump 

I must correct myself: a project will appear in the session list if the teacher is member of this group.
After patching linuxmuster-tools, I get all projects with special chars: https://github.com/linuxmuster/linuxmuster-tools/commit/b94a46f33e5322844d0e0e8c0aae60e8f1754b82

If you do it manually, you will have to restart the webui.

Arnaud
