### ISSUE TITLE
Minor overlay problem:

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-webui7#273]
Ich habe dem Feld in den globalen Einstellungen statt proxyAddresses den Namen "Alternative E-Mail-Adressen" gegeben.
Selbst wenn ich das nicht tue, sehen die Screenshots etwas awkward aus :)

![grafik](https://github.com/linuxmuster/linuxmuster-webui7/assets/2824334/a8a514c2-ad5f-41d8-b478-15f4ca910212)

ebenso:

![grafik](https://github.com/linuxmuster/linuxmuster-webui7/assets/2824334/83248b15-1f02-4336-ae82-6b5232c1c784)

VG, Tobias

**Comment by jolly-jump** [comment]
Wenn schon:

Als global-admin kann ich bei Lehrern auch die proxyAddresses eingeben, sieht ebenso seltsam aus:

![grafik](https://github.com/linuxmuster/linuxmuster-webui7/assets/2824334/1ddaaf06-9661-4895-9116-6fb73893148d)

**Comment by jolly-jump** [comment]
Super, Thanks!

Kleinigkeit: ein Leerzeichen fehlt, sobald in der User-Ansicht mehrere ProxyAdressen nebeneinander passen.

![grafik](https://github.com/linuxmuster/linuxmuster-webui7/assets/2824334/4b4e07de-e333-4699-b9bf-66f40629bb11)

**Comment by kiarn** [comment]
Hi,

I'm not sure I understand what you mean: do you speak of some margin between the lines ?

**Comment by jolly-jump** [comment]
When aliases are short, there are two adresses in one line. But within the line between two (oder more) adresses, there is no whitespace, eg. like this:

proxyaddress1@domain.deproxyaddress2@domain.de

I'll send you an unredacted version in private, if you want.
