### ISSUE TITLE
error while trying shutdown/restart windows clients from webui

### ISSUE THREAD

**Issue by michaelkohls** [linuxmuster/linuxmuster-webui7#277]
When trying to shutdown or reboot a windows client from webui (device-manager) a server error occurs. 
![grafik](https://github.com/user-attachments/assets/414cd5b3-62a7-46cb-b222-3a3112be861c)

**Comment by kiarn** [comment]
@hermanntoast : can you please have a look at this ?

Thanks ;)

**Comment by hermanntoast** [comment]
The subprocess.Popen could not run because of an additional logging in Ajenti. I will provide a fix for this.
