### ISSUE TITLE
sophomorix-check --analyze-encoding /path/...

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#30]
sophomorix-check now analyzes encoding without locking sophomorix. (starting with 5.52.3-1)

Please verify if that this works for webui now.

**Comment by PLanB2008** [comment]
Unfortunately this does not work. It took me a while to figure out what goes wrong.

By creating a small shellscript which runs the analyze commands simultaneously, like the webui does, you can see that in some cases theres no proper json outout.

The following script:

    #!/bin/bash
    sophomorix-check --analyze-encoding /etc/linuxmuster/sophomorix/default-school/extrastudents.csv -j 1> /dev/null 2> extrastudents.log &
    sophomorix-check --analyze-encoding /etc/linuxmuster/sophomorix/default-school/teachers.csv -j 1> /dev/null 2> teachers.log &
    sophomorix-check --analyze-encoding /etc/linuxmuster/sophomorix/default-school/students.csv -j 1> /dev/null 2> students.log &

resulted in:

    total 16
    -rw-r--r-- 1 root root 187 Sep 19 13:19 extrastudents.log
    -rw-r--r-- 1 root root 573 Sep 19 13:19 students.log
    -rw-r--r-- 1 root root 187 Sep 19 13:19 teachers.log

where the big file contains our  expected json output 

    # JSON-begin
    {
       "JSONINFO" : "RESULT",
       "SUMMARY" : [
          {
             "ANALYZE-ENCODING" : {
                "FORMAT_TYPE" : 0,
                "FILE" : "/etc/linuxmuster/sophomorix/default-school/students.csv",
                "ENCODING" : "ASCII",
                "RESULT" : "/etc/linuxmuster/sophomorix/default-school/students.csv is ASCII encoded"
             }
          }
       ],
       "SCRIPTNAME" : "sophomorix-check",
       "OUTPUT" : [
          {
             "TYPE" : "LOG",
             "LOG" : "/usr/sbin/sophomorix-check terminated regularly"
          }
       ],
       "JSONCOMMENT" : "---"
    }
    
    # JSON-end

and the other 2 containing 

    Failed to open /tmp/net_conf_list: No such file or directory at /usr/share/perl5/Sophomorix/SophomorixBase.pm line 3964.
    rm: cannot remove '/tmp/net_conf_list': No such file or directory

So it seems like theres still a problem  running these commands at the very same time

**Comment by jeffbeck** [comment]
Each config read action creates a tmpfile for the output of `net conf list`.
This was the same file for each script run. Now the file name is randomized, so that concurrent script runs do not interfere each other.

Closed in V-3.60.16-1
