### ISSUE TITLE
Location, State and Country Code are required in webUI7

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#33]
Location, State and Country Code are required in webUI7, but IMHO it shouldn't be like that, because it is not necessary if you do the setup via command line.

**Comment by PLanB2008** [comment]
Did you double check this? AFAIK it is necessary for creating the ssl certificate. I'm not sure but I think the CLI setup Wizard is deprecated and kind of abandoned. 
@HappyBasher do you still maintain the cli setup wizard?

**Comment by HappyBasher** [comment]
Yep. In fact Location, State and Country Code are not absolutely necessary to create a self signed certificate. Setup uses only the fqdn.

**Comment by zefanja** [comment]
> I think the CLI setup Wizard is deprecated and kind of abandoned

I was thinking about `linuxmuster-setup`, not the wizard.

**Comment by PLanB2008** [comment]
Okay. I think it makes sense for users to add these information but I'm gonna make these non mandatory.
