### ISSUE TITLE
No option to edit DHCP lease from webUI

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#35]
I couldn't find a way to edit the DHCP range during setup. Is it hidden somewhere? If you do the setup via CLI you can set the DHCP range.

**Comment by PLanB2008** [comment]
Like in https://github.com/linuxmuster/linuxmuster-webui7/issues/33#issuecomment-428180283
I don't know if the CLI wizard is still maintained. On the other hand this option still exists.

I'm not sure if we'll provide this option from the beginning. We once hat this option but removed it later to the bare minimum.
Maybe we'll add it as a expert setting or something like that.

**Comment by zefanja** [comment]
>  Maybe we'll add it as a expert setting or something like that.

:+1: or a setting, where you can change the DHCP lease range later.

**Comment by kiarn** [comment]
Hello,

So, it's not so complicated, we just have to read `/etc/linuxmuster/subnets.csv` with a CSV-Parser, and then run `linuxmuster-import-subnets`.

I will discuss this with the other devs.

**Comment by kiarn** [comment]
Hello,

Done : 
https://github.com/linuxmuster/linuxmuster-webui7/commit/82db2c1fbb3ec9f8a4bf9ef4164cc82e7b4eb42f
https://github.com/linuxmuster/linuxmuster-webui7/commit/d066e3c71c839ddbcdd4569bd2fdc7984e831c38
https://github.com/linuxmuster/linuxmuster-webui7/commit/61f5f85d1f632f19b9ad85295dcbc9a7964ebc40
https://github.com/linuxmuster/linuxmuster-webui7/commit/35af248db198df0e49af6e359882f5ab0e29f966

There's no validation for the fields, but an alert and confirmation if someone want to delete a subnet.
If this setting tab is too dangerous, we can comment it until this is safe.

**Comment by kiarn** [comment]
This is now published in version 7.1.
