### ISSUE TITLE
Country code should be renamed to language in setup

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#37]
The country code in the setup routine sets the language in config.yml. It would be better to rename it as Language, because in some countries you speak more than just one language. (e.g. in Switzerland they have 3 languages).

**Comment by zefanja** [comment]
In the latest version its "Country" again (instead of Language).

**Comment by zefanja** [comment]
I've just run the setup wizard and it is back to "Country" again, but actually you set the language in this field:

https://github.com/linuxmuster/linuxmuster-webui7/blob/a8d71b773038f238c04411febbc02445679e120c/usr/lib/linuxmuster-webui/plugins/lmn_setup_wizard/partial/init-school.html#L21

https://github.com/linuxmuster/linuxmuster-webui7/blob/a8d71b773038f238c04411febbc02445679e120c/usr/lib/linuxmuster-webui/plugins/lmn_setup_wizard/partial/init-summary.html#L19

**Comment by zefanja** [comment]
Still an issue, should be opened again.

**Comment by PLanB2008** [comment]
I'll look into this again. If I recall correctly this is used for language AND for the ssl certificate country.

**Comment by kiarn** [comment]
This parameter is saved as language in the Webui, and as `country` in `setup.ini`, but I was not able to find any use of this parameter in https://github.com/linuxmuster/linuxmuster-base7, even for the certificate. So I changed back the label to language, and updating this is not a big deal, so we can close this.

**Comment by kiarn** [comment]
I got the confirmation of @HappyBasher that this is not used anymore in `linuxmuster-base7`.
