### ISSUE TITLE
bindpw of global-admin is readable for everyone

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#38]
If I go to the login page and show the source code of the page, all content (including `bindpw` and `binddn` for the global admin) is readable in plaintext by everyone...

**Comment by kiarn** [comment]
Hello,

Ajenti build a dict with the config content, then pass it to AngularJS, but I think we don't need the key linuxmuster in AngularJS, all the ldap connect is done within the lm_* plugins with Python.

I can simply delete this key in the dict.

@PLanB2008 : can you please confirm ?

**Comment by PLanB2008** [comment]
This is right. We don't need these information in frontend. @kiarn any suggestions how to fix this backwards in ajenti core? I guess its pretty easy in linuxmuster-core but I think we need a quick solution for this issue.
