### ISSUE TITLE
WebUI should forward to HTTPS after setup

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#39]
After the setup and a reboot the webUI is only accessible over HTTPS, but it does not forward HTTP requests to HTTPS. For a better user experience it should do it.

**Comment by kiarn** [comment]
Hello @zefanja ,

Thanks for your report. I searched a long time a solution for this issue, and I think it will be difficult to redirect to HTTPS with WebSockets. Wenn SSL is enabled, the server only decode SSL requests, and, as far as I know, it is not possible to listen to HTTP and HTTPS on the same port.

So, for the moment I didn't find a simple solution, but I will search further.

**Comment by zefanja** [comment]
One way to solve this would be proxy server, like nginx. Nginx could take care of all the redirection and also provide a nicer domain like _webui.domain.tld_

**Comment by netzint** [comment]
> One way to solve this would be proxy server, like nginx. Nginx could take care of all the redirection and also provide a nicer domain like _webui.domain.tld_

We do not want that explicitly. If it has to go through a reverse proxy, then via the OPNsense. I see the problem as less tragic. Many web applications only listen to SSL. A shortcut or a 1 Click APP should help you better.

**Comment by zefanja** [comment]
I understand that, but software should also be written to be easy to support. Maybe it's just me, but I fear that we will have many questions like "I can't access the webUI after installation anymore". There should be a solution for that. 

> Many web applications only listen to SSL

Yes, and most of them redirect from HTTP to HTTPS :)

**Comment by kiarn** [comment]
I have had the confirmation today : it's not possible with gevent to split the different requests HTTP and HTTPS. The only way to do this is to install nginx or apache, and to let this run as a proxy_pass.

You can see the config file for nginx here : https://support.ajenti.org/knowledge-bases/5/articles/1129-ajenti-behind-nginx, it's quite the same way for apache.
