### ISSUE TITLE
webUI / ajenti tries to track users

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#44]
There seems to be some code inside ajenti, that tries to track their users. ~~Luckily its blocked (CORS)~~ **Its blocked only in Firefox, not in Chromium/Chrome!**:

![auswahl_189](https://user-images.githubusercontent.com/708888/46703857-bb815500-cc52-11e8-8823-5fc0481a5b26.png)

**Comment by PLanB2008** [comment]
Well this is a leftover we got by the ajenti base. It doesn't look like a big deal to remove.
We'll definitely  remove this in a feature release.

**Comment by PLanB2008** [comment]
@kiarn do you see a fix for this?

**Comment by kiarn** [comment]
I think 8062516 should solve this.

To be sure, please try on your own testserver the following commands : 

        cd /usr/local/lib/python2.7/dist-packages/ajenti_plugin_core
        sed -i 's/true/false/g' resources/js/core/services/feedback.service.es
        /usr/local/bin/ajenti-dev-multitool --build

Any feedback welcome !

**Comment by PLanB2008** [comment]
Hi @kiarn this does not work because we do not install dev-multitool as an requirement.

**Comment by kiarn** [comment]
I'm afraid this will be a little more complicated then, I have to test it further.

**Comment by kiarn** [comment]
Solved in the next release from Ajenti https://github.com/ajenti/ajenti/commit/4b8394fe6c00bce1145c40727fb1aecbee25633f
See https://github.com/linuxmuster/linuxmuster-webui7/blob/alpha/usr/lib/linuxmuster-webui/plugins/lmn_common/resources/js/module.coffee#L15

**Comment by zefanja** [comment]
Looks like it is enabled again... https://ask.linuxmuster.net/t/sophomorix-check-sophomorix-add-sophomorix-update-schleife/3967/22
