### ISSUE TITLE
Adding a new student causes a faulty entry in studenty.csv

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#45]
If you click "Schüler hinzufügen" and then save the file, it causes a faulty entry in students.csv (because of the "New" value in "Vorname")

![auswahl_190](https://user-images.githubusercontent.com/708888/46704001-4bbf9a00-cc53-11e8-87c1-893f32789728.png)

It would be nice, if there is some input validation.

That is try for all lists (teachers, extra students) when you click on "Add Teacher/Students" and save it, without entering something in the empty line.

**Comment by PLanB2008** [comment]
I'll have a look where the 'New' comes from. This afaik this does not happen in teacher module and I'm gonna remove this.

Saving empty lines is currently expected but I think we can add some validation in feature.

**Comment by PLanB2008** [comment]
I added support for this. Right now theres only a message which appears if there are missing information in a new line.
In feature the bad line should be highlighted.
