### ISSUE TITLE
Can't remove student from session

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#46]
If I want to remove a student from a session, he/she re-appears.
![peek 2018-10-10 18-49](https://user-images.githubusercontent.com/708888/46734419-56af1480-ccbd-11e8-8713-dca54c91602d.gif)

**Comment by PLanB2008** [comment]
This only happens to the last user in a session, right? 
I assume this is an issue based on the way I write the sessionmembers. I'll have a look into this.

**Comment by zefanja** [comment]
Yes, only happens with last student.

**Comment by PLanB2008** [comment]
I passed this problem to @jeffbeck  
https://github.com/linuxmuster/sophomorix4/issues/58
The module writes all session members back in one string rather than running add-user and remove-user several times.
This works almost flawless except if the participant string is empty.

**Comment by PLanB2008** [comment]
fixed
