### ISSUE TITLE
Can't delele users

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#51]
The Delete action does not work. Nothing happens, when I click the button:
![peek 2018-10-10 20-12](https://user-images.githubusercontent.com/708888/46738956-a1cf2480-ccc9-11e8-8c81-832f1f630f96.gif)

There is no delete for students.

EDIT: Or is the only way to delete a user, to remove the entry in the corresponding csv file?

**Comment by PLanB2008** [comment]
Please always add the information in which usermmodule this happens.
I assume this is the teacher Module? 
Indeed there should be no delete option.
Only school- and globaladministrators can be added without list editing.

**Comment by zefanja** [comment]
Sorry, yes, it's the teacher module.
