### ISSUE TITLE
Print Passwords as root user results in error

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#54]
When I click on "Print Passwords" as root user, I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 378, in handle_api_users_print
    return lmn_getSophomorixValue(sophomorixCommand, 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/'+school)
  File "/usr/lib/linuxmuster-webui/plugins/lm_common/api.py", line 155, in lmn_getSophomorixValue
    'Error Message: ' + str(e) + '\n Dictionary we looked for information:\n  ' + str(jsonDict))
Exception: getSophomorix Value error. Either sophomorix field does not exist or ajenti binduser does not have sufficient permissions:
Error Message: 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/default-school'
 Dictionary we looked for information:
  {u'JSONINFO': u'PRINTDATA', u'LIST_BY_sophomorixCreationDate': {}, u'LISTS': {u'sophomorixCreationDate': []}, u'JSONCOMMENT': u'Printable Data', u'RESULT': {u'BACK_IN_TIME_MAX': -1, u'user': {u'student': {u'COUNT': u'0'}}, u'HISTORY': {u'TOTAL': 0}}}
```

**Comment by PLanB2008** [comment]
Well first and for all printing passwords as root isn't particularly supported.

The 'right' way of using the WebUI should be to login as a systemuser like global-admin.

Do you still have the user global-admin? Back then I implemented a fallback if root user is logged in for the printer module. In this case it'll take global-admin as the caller of the command.

Does the module work using a teacher or administrative user?

**Comment by zefanja** [comment]
> Well first and for all printing passwords as root isn't particularly supported.

Well, then there should be not "Print Passwords" if you login as root :) Or disable root login.

> The 'right' way of using the WebUI should be to login as a systemuser like global-admin.

Also for the initial setup?

> Does the module work using a teacher or administrative user?

If I login with the global-admin I get this error (with no students and teacher users):

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 378, in handle_api_users_print
    return lmn_getSophomorixValue(sophomorixCommand, 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/'+school)
  File "/usr/lib/linuxmuster-webui/plugins/lm_common/api.py", line 155, in lmn_getSophomorixValue
    'Error Message: ' + str(e) + '\n Dictionary we looked for information:\n  ' + str(jsonDict))
Exception: getSophomorix Value error. Either sophomorix field does not exist or ajenti binduser does not have sufficient permissions:
Error Message: 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/default-school'
 Dictionary we looked for information:
  {u'JSONCOMMENT': u'Printable Data', u'LIST_BY_sophomorixCreationDate': {}, u'JSONINFO': u'PRINTDATA', u'LISTS': {u'sophomorixCreationDate': []}, u'RESULT': {u'BACK_IN_TIME_MAX': -1, u'user': {u'student': {u'COUNT': u'0'}}, u'HISTORY': {u'TOTAL': 0}}}
```

As a teacher it does work.

**Comment by PLanB2008** [comment]
> > Well first and for all printing passwords as root isn't particularly supported.
> 
> Well, then there should be not "Print Passwords" if you login as root :) Or disable root login.
Ya this is planned for the feature. For the current dev process it makes sense not to disable it but I agree, its kind of conusing in this state. Sorry for that.

> 
> > The 'right' way of using the WebUI should be to login as a systemuser like global-admin.
> 
> Also for the initial setup?
No, not for the initial setup. At this point there are no systemuser so we need a unix user to authenticate. This is an documentation issue rather than a technical one.

> 
> > Does the module work using a teacher or administrative user?
> 
> If I login with the global-admin I get this error (with no students and teacher users):
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
>     result = fx(self, context, *args, **kwargs)
>   File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 378, in handle_api_users_print
>     return lmn_getSophomorixValue(sophomorixCommand, 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/'+school)
>   File "/usr/lib/linuxmuster-webui/plugins/lm_common/api.py", line 155, in lmn_getSophomorixValue
>     'Error Message: ' + str(e) + '\n Dictionary we looked for information:\n  ' + str(jsonDict))
> Exception: getSophomorix Value error. Either sophomorix field does not exist or ajenti binduser does not have sufficient permissions:
> Error Message: 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/default-school'
>  Dictionary we looked for information:
>   {u'JSONCOMMENT': u'Printable Data', u'LIST_BY_sophomorixCreationDate': {}, u'JSONINFO': u'PRINTDATA', u'LISTS': {u'sophomorixCreationDate': []}, u'RESULT': {u'BACK_IN_TIME_MAX': -1, u'user': {u'student': {u'COUNT': u'0'}}, u'HISTORY': {u'TOTAL': 0}}}
> ```
This appears to be a bug. I'll have a look into this.

EDIT: Looks like the same error message you got using root. So at least the workaround "use global-admin if root is logged in" seems to be intact.
> 
> As a teacher it does work.

Thanks for reporting.

**Comment by PLanB2008** [comment]
> > Well first and for all printing passwords as root isn't particularly supported.
> 
> Well, then there should be not "Print Passwords" if you login as root :) Or disable root login.
> 
> > The 'right' way of using the WebUI should be to login as a systemuser like global-admin.
> 
> Also for the initial setup?
> 
> > Does the module work using a teacher or administrative user?
> 
> If I login with the global-admin I get this error (with no students and teacher users):
> 
> ```
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
>     result = fx(self, context, *args, **kwargs)
>   File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 378, in handle_api_users_print
>     return lmn_getSophomorixValue(sophomorixCommand, 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/'+school)
>   File "/usr/lib/linuxmuster-webui/plugins/lm_common/api.py", line 155, in lmn_getSophomorixValue
>     'Error Message: ' + str(e) + '\n Dictionary we looked for information:\n  ' + str(jsonDict))
> Exception: getSophomorix Value error. Either sophomorix field does not exist or ajenti binduser does not have sufficient permissions:
> Error Message: 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/default-school'
>  Dictionary we looked for information:
>   {u'JSONCOMMENT': u'Printable Data', u'LIST_BY_sophomorixCreationDate': {}, u'JSONINFO': u'PRINTDATA', u'LISTS': {u'sophomorixCreationDate': []}, u'RESULT': {u'BACK_IN_TIME_MAX': -1, u'user': {u'student': {u'COUNT': u'0'}}, u'HISTORY': {u'TOTAL': 0}}}
> ```
> 
> As a teacher it does work.

Okay, i've to ask further. Does the module work using another global-administrator? What about a school-administrator?

I don't exactly get the circumstances when this happens.

**Comment by zefanja** [comment]
This is the output when I log in as school-admin:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 377, in handle_api_users_print
    return lmn_getSophomorixValue(sophomorixCommand, 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/'+school)
  File "/usr/lib/linuxmuster-webui/plugins/lm_common/api.py", line 155, in lmn_getSophomorixValue
    'Error Message: ' + str(e) + '\n Dictionary we looked for information:\n  ' + str(jsonDict))
Exception: getSophomorix Value error. Either sophomorix field does not exist or ajenti binduser does not have sufficient permissions:
Error Message: 'LIST_BY_sophomorixSchoolname_sophomorixAdminClass/default-school'
 Dictionary we looked for information:
  {u'JSONINFO': u'PRINTDATA', u'LIST_BY_sophomorixCreationDate': {}, u'LISTS': {u'sophomorixCreationDate': []}, u'JSONCOMMENT': u'Printable Data', u'RESULT': {u'BACK_IN_TIME_MAX': -1, u'user': {u'student': {u'COUNT': u'0'}}, u'HISTORY': {u'TOTAL': 0}}}

```

**Comment by PLanB2008** [comment]
Well, if the output is correct, there are no students:
 {u'student': {u'COUNT': u'0'}},
Do you have added any students?

**Comment by zefanja** [comment]
yes, there are no students.

**Comment by PLanB2008** [comment]
Okay, so we get closer. Could you add students and try again?

Seems like an easy bug and we just have to check if there are students before we try offering the class overview.

**Comment by zefanja** [comment]
When I add a student, it works.

**Comment by PLanB2008** [comment]
Okay so in this case we've to check if there are any students first...
