### ISSUE TITLE
Linbo Module - UI bugs

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#55]
I created a new start.conf from a template and gave it a name ("Ubuntu"). The name is not displayed in the detailed settings, just "gruppe". When I create a new start.conf (empty, not a template) it works. 

There are also JSON data displayed in the partitions screen.

![auswahl_193](https://user-images.githubusercontent.com/708888/46803673-d8b93f00-cd8a-11e8-963b-47cc10bdd5c8.png)

**Comment by PLanB2008** [comment]
Well the Json output is more or less a reminder to implement (user)configurable disk Types like mmcblk and nvme.
