### ISSUE TITLE
WebUI - Settings: SSL

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#59]
Having chosen the menue general -> settings in the WebUI. I ticket SSL activate, I haven chosen the SSL certificate generated during setup - apperently the wrong one -, saved the settings and restarted the panel.
No error warning and no access to the WebUI anymore.
Having found that the settings are saved in /etc/ ajenti/ config.yml I can reset them.

It would be helpful, if there could be any hints or checks for the correct ssl certificate file.

**Comment by kiarn** [comment]
Hello @cweikl,

Thanks for your report, it is not a big deal to solve this ( I already have a solution ), but we have to modify ajenti-plugin-core for this.

**Comment by kiarn** [comment]
Pull request here ajenti/ajenti#1149.

**Comment by kiarn** [comment]
Merged in Ajenti.
