### ISSUE TITLE
WebUI: Several Menue items fail - linuxmuster-webui7 1.0.18-41

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#60]
Having chosen the menue option Global-Admins (user-management) I receive a warning indicationg a server error. 
No JSON object could be decoded. 

Request POST /api/lm/sophomorixUsers/globaladmins
Type ValueError

**Comment by cweikl** [comment]
The same is true for all submenues in the menue "user management" and for the menue items "List Management - students list & lehrer-Liste", also for "Class Management - Passwörter drucken" and for both submenues for "school settings"

**Comment by kiarn** [comment]
Hello @cweikl ,

First of all : do you have some users on your system ?
You can check it with : 

`sophomorix-user -i`

**Comment by cweikl** [comment]
Hi @kiarn,
ok, I checked it with your proposed command. I receive an error message:
"ERROR: Connection to AD failed: No password found!"
There are some hints how to connect to AD.
I thought having done the setup with WebUI that AD has been configured.
Then I tried to create a new user administrator, but I receive an ERROR as samba-tool is unable to parse dn string.
/etc/linuxmuster/.secret/administrator does not exist.
How can I start the setup with the WebUI again ?

**Comment by PLanB2008** [comment]
Sound like a serious bug. Could you describe your steps from the beginning?
It seems something went wrong during the installation.

**Comment by cweikl** [comment]
ok, I have done the following steps:

1. Imported the OVA VMs in XCP
2. Followed the steps in the github wiki to prepare these VMs for usage with v7
3. updated all VMs
4. rebooted all VMs
5. checked connectivity for internal and external network
6. configured a notebook to be part of the internal network
7. opend the browser (firefox) and used the URL: http://10.16.1.1:8000
8. I logged in with the root credentials of server
9. I followed the setup-routine of the WebUI indicating to configure Firewall, docker and OPSI
10. saw the end of log file - OPSI could not be reached - which was true as I have forgotten to star the VM.
11. checked the log in the server - alls steps indicated success
10. Afterwards I signed in with the root credentials and started to use the WebUI with the above mentioned errors.

**Comment by PLanB2008** [comment]
Is this still a problem? I would suggest to start over using the current ova and try again.
