### ISSUE TITLE
WebUI does not show up with MS Edge Browser 

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#61]
I tried you login to the WebUI, but using MS Edge Browser does not show up any content of the WebUI, so I cannot see any login fields.
I am using win10 Pro N in a VM with updates installed (status yesterday).
Is this a know behaviour of the WebUI?

**Comment by zefanja** [comment]
Any errors in the web console of the Edge Browser?

**Comment by cweikl** [comment]
No, I only see a shaded column without content on the left side of the window.

**Comment by zefanja** [comment]
So, no errors in the console (https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide/console)?

**Comment by cweikl** [comment]
Ah, thanks for the hint.
In the console window I receive the following errors:
`DOM97011: Der Code auf dieser Seite hat die Zwischenspeicherung und das Vor- und zurücknavigieren deaktiviert.
Script1004: Expected ; 
all.js (2143,22)
Script5022: [$injector:nomod]: Module core ist not available. ...
all.bendor.js (2056,11)`

**Comment by kiarn** [comment]
Hello,
I've already solved it last week on a fork : https://github.com/ajenti/ajenti/issues/1117#issuecomment-427751808

**Comment by cweikl** [comment]
ok, so with the next update of ajenti this will be fixed for all ?
Thanks

**Comment by PLanB2008** [comment]
Seems like this issue got fixed upstream and should be solved soon for everyone.

**Comment by kiarn** [comment]
Yep, thanks, I didn't see it.

**Comment by kiarn** [comment]
@cweikl : does it work with the version 2.1.25 ?

**Comment by PLanB2008** [comment]
@kiarn this seems to work now, just tested 2.1.25
![peek 2018-12-06 16-53](https://user-images.githubusercontent.com/26460239/49595429-3bd4e580-f978-11e8-8f2f-c8b925d6a652.GIF)
