### ISSUE TITLE
Linbo: Groups start.conf 

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#62]
I have two start.conf files for two hardware classes. After running linuxmuster-import-devices, I do not get any errors. In the start.conf files I used previous definitions as I use them under v6.2.

For a Win7 group I can edit the group via WebUI. Habing changed the size of the windows partition I saved the changed with the webUI. Looking in the start.conf.win7 file in /etc/linuxmuster/linbo the changes are not reflected.
Where does the WebUI save the start.conf files.
I thought I use the correct directory as an import of devices without a start.conf for a used group fails.

**Comment by PLanB2008** [comment]
Sorry for the late response.

start.conf are saved in the linbo directory like it was in 6.2 as well. This changed from ''/var/linbo/'' to ''/srv/linbo/''

**Comment by cweikl** [comment]
Yes, it works as you indicated. The new directory for linbo is now /var/linbo.
All config-files are saved in this directory and changes are definitely saved.
It works. Sorry for any confusions.
