### ISSUE TITLE
WebUI: Ajenti core 2.1.24 update to 2.1.25 available - fails

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#63]
I logged in the WebUI as a superuser. Under Plugins it is indicated, that an update of Ajenti Core to version 2.1.25 is available.

I clicked update everything on top the page and I receiven an error:

`Upgrading Ajenti: Failed erno 2 no such file or directory`

**Comment by kiarn** [comment]
Hello @cweikl,

Yes, the file ajenti-update is missing, that's the reason.
It's not perfect, but here you can update manually with CLI : 

    pip install aj -U
    systemctl restart linuxmuster-webui.service

**Comment by kiarn** [comment]
Hello @cweikl,

Can you please show the output of 
`ls /usr/local/bin/`
?

**Comment by cweikl** [comment]
Hi @kiarn,

I have manually updated as you proposed above.
The output of /usr/local/bin is as follows:
`ajenti-client-ssl-gen
ajenti-panel
ajenti-ssl-gen
easy_install
easy_install-2.7
pip
pip2
pip2.7
wheel
`

**Comment by kiarn** [comment]
Ok, thanks, we have to correct the setup process, which forgot to move ajenti-upgrade.

**Comment by kiarn** [comment]
Corrected in Ajenti with ajenti/ajenti#1140
I think it can be solved through : 

```
pip uninstall ajenti-panel
pip install ajenti-panel
```

It worked for me.

**Comment by PLanB2008** [comment]
@kiarn this should be solved, right? Close?

**Comment by kiarn** [comment]
It's solved : the file requirements.txt specifies ajenti in version 2.1.26 which solves this, so it's good for all new install. We can manually solve the other : https://github.com/ajenti/ajenti/issues/1143
