### ISSUE TITLE
Exam collection foldername and structure

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#64]
When collecting an exam (multiple classes, 100 users),

the following data structure is favorited by the teachers that do such things:

Date-Name_of_session
    ├── class1
    │   ├── Lastname2_Firstname2_loginname_hostname
    │   └── Lastname_Firstname_loginname_hostname
    ├── class2
    └── class3

Very important is Lastname_Firstname instead of login_name.

Firstname/Lastname could be acsii- versions to avoid file naming problems.

**Comment by PLanB2008** [comment]
Sounds reasonable. I'm gonna try to implement it that way.
