### ISSUE TITLE
debian pckage update of linuxmuster-webui7 on a not configured server needs to show information

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#68]
when you update linuxmuster-webui7 BEFORE linuxmuster-setup:

--> The postinstscript fails, because there is no password to connect to samba.

There should be:

1) a message what to to manually (in the webui package) like:
    Please run dpkg-reconfigure linuxmuster-webui7 after setup
2) Is this done by the linuxmuster-setup?

**Comment by PLanB2008** [comment]
Can you provide a error message?

**Comment by PLanB2008** [comment]
I assume this is related to sophomorix-ui ? We could check if setup is done before we try to run sophomorix-ui.

Would this solve the problem?

**Comment by kiarn** [comment]
Is it still a thing, or can we close it ?
I was never able to see this kind of behaviour during an update or a new install.

**Comment by kiarn** [comment]
This seems to be solved now.
