### ISSUE TITLE
Can't add a student with unicode chars

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#69]
When I want to add a student, that has a unicode char (e.g. André) I get this error:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/aj/api/endpoint.py", line 74, in wrapper
    result = fx(self, context, *args, **kwargs)
  File "/usr/lib/linuxmuster-webui/plugins/lmn_users/views.py", line 57, in handle_api_students
    ).writerows(data)
  File "/usr/lib/python2.7/csv.py", line 158, in writerows
    return self.writer.writerows(rows)
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 90, in writerows
    self.writerow(row)
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 86, in writerow
    _stringify_list(row, self.encoding, self.encoding_errors))
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 48, in _stringify_list
    return [_stringify(s, encoding, errors) for s in iter(l)]
  File "/usr/local/lib/python2.7/dist-packages/unicodecsv/py2.py", line 38, in _stringify
    return s.encode(encoding, errors)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xfc' in position 1: ordinal not in range(128)
```

**Comment by kiarn** [comment]
Is it still a problem ?

I cannot reproduce on my system : 

![2019-01-28_11-02](https://user-images.githubusercontent.com/10401079/51828722-80339080-22ec-11e9-89ab-104ce6ee3d52.png)

**Comment by zefanja** [comment]
Yes, still a problem.

Steps to reproduce:
* clean system / fresh install
* add a student with unicode char in the webUI
* error

This is the request: `POST /api/lm/users/students-list?encoding=ASCII` 

Looks like the charset detection is wrong. Encoding is set to `auto` in `school.conf`.

**Comment by jeffbeck** [comment]
The auto detection only works if you use real names (firstnames, lastnames).
If you type in arbitrary unicode characters ist simply a guess.
Maybe I can improve the guess.
Pleas write back the output of the following command to make sure I understand what you are doing.

and please try to cut and past the file.

sophomorix-check  --analyze-encoding /path/to/students.csv

**Comment by zefanja** [comment]
I am using a proper name (André Mustermann), but it looks like its a webUI issue and not a sophomorix. I can't even save an entry with unicode characters to the file. Here is a screenshot of the error:

![grafik](https://user-images.githubusercontent.com/708888/51872436-faffb880-238b-11e9-8d8f-a218634a5559.png)

**Comment by zefanja** [comment]
`sophomorix-check --analyze-encoding /path/to/students.csv` (on empty students file, because I haven't added a student yet):

```
Command line::
Hmmh. do not know what to do with option info
Option json is a modifier option
Option verbose is a modifier option
* forcing info mode
Option combinations successfully checked
OK: SophomorixSchemaVersion 1 matches required Version 1
#### Reading /usr/share/sophomorix/devel/sophomorix.ini                   ####
Distro-check: Ubuntu 18.04 is OK
#### Reading /etc/samba/smb.conf                                          ####
#### Reading /usr/lib/linuxmuster-webui/etc/default-ui-permissions.ini    ####
#### Parsing: net conf list                                               ####
#### Asking domain passwordsettings from samba                            ####
#### Reading /usr/share/sophomorix/devel/master/sophomorix.conf.master    ####
#### Reading /etc/linuxmuster/sophomorix/sophomorix.conf                  ####
#### OK: default-school share exists                                      ####
#### OK: /etc/linuxmuster/sophomorix/default-school/school.conf           ####
#### Reading /usr/share/sophomorix/devel/master/school.conf.master        ####
#### Reading /etc/linuxmuster/sophomorix/default-school/school.conf       ####
#### Encode-analyze students.csv                                          ####

Encoding check result for:
   /etc/linuxmuster/sophomorix/default-school/students.csv

Unknown firstnames (Please report to info@linuxmuster.net):
+------------------------------------------+
+------------------------------------------+

Firstnames that should be an error (Please report the the School Office):
+---------------------------------------------------------------------------+

Unknown lastnames (Please report to info@linuxmuster.net):
+------------------------------------------+
+------------------------------------------+

Lastnames that should be an error (Please report the the School Office):
+---------------------------------------------------------------------------+

                      +-----------------+-----------------+         
                      |    firstname    |     surname     |         
+---------------------+--------+--------+--------+--------+--------+
| Tested Encodings:   |   Hits | Errors |   Hits | Errors |    Sum |
+---------------------+--------+--------+--------+--------+--------+
| UTF8                |      0 |      0 |      0 |      0 |      0 |
| ISO_8859-1          |      0 |      0 |      0 |      0 |      0 |
+---------------------+--------+--------+--------+--------+--------+
| none of the above   |      0 |      - |      0 |      - |      - |
+---------------------+--------+--------+--------+--------+--------+
/etc/linuxmuster/sophomorix/default-school/students.csv:
    File-Encoding is ASCII

#### /usr/sbin/sophomorix-check terminated regularly                      ####
Calling console printout
LOG       : /usr/sbin/sophomorix-check terminated regularly                   
RESULT    : /etc/linuxmuster/sophomorix/default-school/students.csv is ASCII encoded

```

**Comment by jeffbeck** [comment]
This part is tricky for the the webui and not top priority. 
I hope Andy does things that are more urgent for the beta

**Comment by zefanja** [comment]
I just report bugs :) 

When I'm a new user and want to add my first student through the webUI and I can't because of an encoding issue...

From my point of knowledge default encoding should be utf8 if the file is empty, otherwise use the encoding of the (imported) file or utf8 for everything (writing / saving). But you know this better.

**Comment by PLanB2008** [comment]
Ya this is kind of tricky.

This is how it works at the moment:

WEBUI looks for the encoding configuration, if this is set to auto it uses sophomorix analyze to get the encoding.
If the file is empty youll get ASCII I guess. In this case it cannot write unicode chars.

Using the upload button it is supposed to analyze the encoding first and render the student data afterwards properly (not fully implemented yet).

Maybe @zefanja is right and we should assume utf8 if the file is empty @jeffbeck what do you think? This would solve the chicken or egg problem

**Comment by PLanB2008** [comment]
Ya this is kind of tricky.

This is how it works at the moment:

WEBUI looks for the encoding configuration, if this is set to auto it uses sophomorix analyze to get the encoding.
If the file is empty youll get ASCII I guess. In this case it cannot write unicode chars.

Using the upload button it is supposed to analyze the encoding first and render the student data afterwards properly (not fully implemented yet).

Maybe @zefanja is right and we should assume utf8 if the file is empty @jeffbeck what do you think? This would solve the chicken or egg problem

**Comment by jeffbeck** [comment]
For analyzing an empty file, the result could be utf8, no problem.

I will open an issue for that in sophomorix4

**Comment by zefanja** [comment]
I did some further testing. This is not a problem of an empty file only. When I only have "non-unicode" students in the students.csv and I want to add one with a special letter (like é) - the same error happens, because sophomorix detects ASCII. 

Is there a reason why the files should be saved in different encodings? Why not just use utf-8 by default? Isn't the encoding detecting not only important for imported files or reading in general? For saving the data it could be utf-8, isn't it?

**Comment by PLanB2008** [comment]
You could be right zefanja, didn't think about it this way.
@jeffbeck what do you think?

**Comment by jolly-jump** [comment]
Hi, also teacher, 

the simplest documentation does not work, since I only want to add a single teacher user with äöü..

cheers, Tobias

**Comment by zefanja** [comment]
I should work if you add a teacher manually in the techers.csv with a unicode character. The webUI checks the encoding of the *.csv files before saving it. Adding a unicode character in the *.csv should "fix" it.

**Comment by jolly-jump** [comment]
Hi.
Yes, but it is supposed for the simple case: add a teacher to the webui, which is not possible at the moment.
If I set the encoding to UTF-8 in the WEbui than add  a teacher, even if it does not contain any äöü, it does produce an browser console error, not the erro dialog.
see attached.

**Comment by jolly-jump** [comment]
![Screenshot at 2019-03-24 09:44:12](https://user-images.githubusercontent.com/2824334/54877087-24801200-4e1a-11e9-9fac-3c6b97daa460.png)

now the upload

**Comment by PLanB2008** [comment]
I just looked into this again.

It all boils down to an encoding detection problem.  The error @jolly-jump mentioned is caused by this:

```
 sophomorix-check  -jj

#### Encoding results for  extrastudents.csv                              ####
   * ENCODING:          auto (configured)
   * ENCODING_FORCE:    FALSE
   * ENCODING_CHECKED:  UTF8
           ---> Using:  UTF8
#### Encoding results for  students.csv                                   ####
   * ENCODING:          auto (configured)
   * ENCODING_FORCE:    FALSE
   * ENCODING_CHECKED:  unknown
#### Removing lock in /var/lib/sophomorix/lock/sophomorix.lock            ####
#### ENCODING=auto failed: Set ENCODING to the desired value and ENCODING_FORCE to "True"####
# JSON-begin
{"JSONINFO":"RESULT","OUTPUT":[{"MESSAGE_DE":"ENCODING=auto failed: Set ENCODING to the desired value and ENCODING_FORCE to \"True\"","MESSAGE_EN":"ENCODING=auto failed: Set ENCODING to the desired 
```

Digging deeper we get this:

```
sophomorix-check --anal students.csv

Encoding check result for:
   students.csv

Unknown lastnames (Please report to info@linuxmuster.net):
+------------------------------------------------------------------------------+
| Maßkrug                                 |
+------------------------------------------------------------------------------+

                      +-----------------+-----------------+         
                      |    firstname    |     surname     |         
+---------------------+--------+--------+--------+--------+--------+
| Tested Encodings:   |   Hits | Errors |   Hits | Errors |    Sum |
+---------------------+--------+--------+--------+--------+--------+
| UTF8                |      0 |      0 |      0 |      0 |      0 |
| ISO_8859-1          |      0 |      0 |      0 |      0 |      0 |
+---------------------+--------+--------+--------+--------+--------+
| none of the above   |      0 |      - |      1 |      - |      - |
+---------------------+--------+--------+--------+--------+--------+
students.csv:
    File-Encoding is unknown (Sureness: FALSE)

#### /usr/sbin/sophomorix-check terminated regularly                      ####
Calling console printout
LOG       : /usr/sbin/sophomorix-check terminated regularly                   
RESULT    : students.csv is unknown encoded
```


Removint the student named maßkrug:

```
sophomorix-check --anal students.csv
#### Encode-analyze students.csv                                          ####

Encoding check result for:
   students.csv

                      +-----------------+-----------------+         
                      |    firstname    |     surname     |         
+---------------------+--------+--------+--------+--------+--------+
| Tested Encodings:   |   Hits | Errors |   Hits | Errors |    Sum |
+---------------------+--------+--------+--------+--------+--------+
| UTF8                |      0 |      0 |      0 |      0 |      0 |
| ISO_8859-1          |      0 |      0 |      0 |      0 |      0 |
+---------------------+--------+--------+--------+--------+--------+
| none of the above   |      0 |      - |      0 |      - |      - |
+---------------------+--------+--------+--------+--------+--------+
students.csv:
    File-Encoding is UTF8 (Sureness: TRUE)

#### /usr/sbin/sophomorix-check terminated regularly                      ####
Calling console printout
LOG       : /usr/sbin/sophomorix-check terminated regularly                   
RESULT    : students.csv is UTF8 encoded
```


@jeffbeck 
How should we tackle this? I would suggest something like this:

1 Encoding gets detected when using sophomorix-newfile. 
2 Afterwards it is converted to utf8 / 16. 
3. Webui uses utf8 for everything else, and so does sophomorix-check from there on.

Could we solve this issue in this way?

**Comment by jeffbeck** [comment]
Yes that ist the default behaviour:

register the nwe file with sophomorix-newfile.

This will not convert the file and change nothing on the system:
Reason:

You have very few nonascii Lastnames with umlaut (1, to be precise: maßkrug), and all (here: 1) nonacii characters fail to make 100% sure what encoding this file has.

Add a line like this:

7a;MaierJürgen;10.10.1980;

and Jürgen makes sure, that the encoding can be determined correctly, since Jürgen is a valid Firstname in the firstname databasese

Basing the decision on maßkrug, would be only a guess. And thats not what we want.

**Comment by PLanB2008** [comment]
I get your point.

I'm just thinking if it wouldn't be easier to work with a standardized encoding internally, disconnected by the csv provided.

**Comment by jeffbeck** [comment]
so it is.If the encoding could be determined, it is converted to (internally) utf8.
If you use dummy data like Maßkrug as the only lastname with umlaut. Encoding cannot be detected and manual action is required

**Comment by jeffbeck** [comment]
I checked the following line:

7a;Maßkrug;Jürgen;10.10.1970;

The file is analyzed as utf8 because of the known firstname Jürgen.

So ONE known Firstname or Lastname is enough for encoding detection in a file


Is you use Peter as Firstname, Maßkrug is not enoght to analyze the encoding.

So you problems arise from using funny Names in your small example files.

**Comment by kiarn** [comment]
I think it's solved in testing.
