### ISSUE TITLE
Can't define School-Admins

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#72]
In the user-management I clicked the option School-Admins. As I do not have a schol admin yet, I wanted to add one.
Having clicked this option, I receive a server error.
![error-adding-school-admin](https://user-images.githubusercontent.com/16056720/50919262-9dd6ae00-1442-11e9-8eb6-6a9137f907b7.png)

I receive the same error when trying to do this as global-admin.

**Comment by cweikl** [comment]
Now, testing it with linuxmuster-webui7 1.0.56-1 as global-admin, I still receive an error. 
![bildschirmfoto vom 2019-02-24 19-58-09](https://user-images.githubusercontent.com/16056720/53303804-fdf8a680-386e-11e9-8fc2-458dfd355869.png)

**Comment by PLanB2008** [comment]
This is reported to be fixed now.
