### ISSUE TITLE
Global-Admin: Can't set custom  password

### ISSUE THREAD

**Issue by cweikl** [linuxmuster/linuxmuster-webui7#73]
In the menue Global-Admins, I clicked the option password -> custom password for the global-admin Admin. Then I indicated a new password, clicking OK leads to s server error (Exception, post /api/lm/users/password). 
Please, find attached a screenshot of the error: 
![error-set-global-admin-custom-password](https://user-images.githubusercontent.com/16056720/50919161-551ef500-1442-11e9-93bd-f8be568b773e.png)

I receive the same error, when trying to do this as a global-admin.

**Comment by PLanB2008** [comment]
During the meeting last weekend we figured out there are a lot erros like this. This is based on a changed behaviour in communication between sophomorix and  webui.

I'll fix the issue this week.

**Comment by kiarn** [comment]
In lm_common/api.py : 

    jsonS = subprocess.Popen(sophomorixCommand, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, shell=False)

    while jsonS.poll() is None:
        output = jsonS.stdout.readline()
        file.write(output)

This will log continuously the complete output of sophomorix in your log file. Is that what you need ?
But it's not in json format.
What do you need to extract from the sophomorix command to build the json answer ?

Only this below or more ?

`{"FINAL_STEP":"1","STEP":"1","COMMENT_DE":"Lege Benutzer jlskdjflskdjfsdf, (default-school Admin) an.","COMMENT_EN":"Adding user jlskdjflskdjfsdf, (default-school Admin).","JSONINFO":"PROGRESS"}`

`{"JSONINFO":"RESULT","SCRIPTNAME":"sophomorix-admin","JSONCOMMENT":"---","OUTPUT":[{"NUMBER":-1,"MESSAGE_DE":"FAILED (512): /usr/bin/smbcacls -U administrator%'******' //linuxmuster.lan/default-school management/jlskdjflskdjfsdf, \n      --set \"REVISION:1,OWNER:BUILTIN\\Administrators,GROUP:LINUXMUSTER\\Domain Users,ACL:LINUXMUSTER\\jlskdjflskdjfsdf,:ALLOWED/OI|CI/FULL,ACL:LINUXMUSTER\\global-admins:ALLOWED/OI|CI|I/FULL,\"","TYPE":"ERROR","MESSAGE_EN":"FAILED (512): /usr/bin/smbcacls -U administrator%'******' //linuxmuster.lan/default-school management/jlskdjflskdjfsdf, \n      --set \"REVISION:1,OWNER:BUILTIN\\Administrators,GROUP:LINUXMUSTER\\Domain Users,ACL:LINUXMUSTER\\jlskdjflskdjfsdf,:ALLOWED/OI|CI/FULL,ACL:LINUXMUSTER\\global-admins:ALLOWED/OI|CI|I/FULL,\""},{"TYPE":"LOG","LOG":"/usr/sbin/sophomorix-admin terminated regularly"}]}`

**Comment by PLanB2008** [comment]
Well its a little more complicated.

The output sophomorix provides us in the error level is not clean. There are also some error messages mixed up in it. So I look for #JSON begin and #JSON end strings and split it so I only receive the json string.

**Comment by kiarn** [comment]
Hello @PLanB2008 !

I got both dict above with one single command ( add global-admin in WebUI ), and I extract both of these dicts between # JSON-begin and # JSON-end as you said.

When more than one dict ( between # JSON-begin and # JSON-end ) come as output from a sophomorix command, would you like to merge these ?

**Comment by kiarn** [comment]
Hello @PLanB2008 !

I've done a commit for this in a new branch soph-comm : 0e5b187229dcf8ca6a005f13dd6be508cb3847cf
It seems to work on my server.

Problem was : 

- the string '# JSON-*' was sometime on the same line as the dict,
- null has to be a string 'null', otherwise there's a syntax error.

Please try this and I tell me if it solves this.

**Comment by kiarn** [comment]
We can now set custom password and see first password, there still was an indent problem corrected in 076fda2.

I would recommend to change the text "Show password" into "Show first password", it may confuse some user.

**Comment by kiarn** [comment]
After a couple of tests, I found out that the Json-Dict returned by sophomorix seems to appear in stderr and not in stdout, that's why there are mixed results : the python script scan stdout and stderr.

If it's always the case for all sophomorix command with option `-jj`, it's possible to reduce and optimize a little the python code for `lmn_getSophomorixValue()`.

@jeffbeck : can you please confirm ?

**Comment by PLanB2008** [comment]
Yes thats right, the json output always appear in error level.
Only problem is: the output is not clean json output. Erros appear as well in the output

**Comment by kiarn** [comment]
> Yes thats right, the json output always appear in error level.

Ok, thanks.

> Only problem is: the output is not clean json output. Erros appear as well in the output

I've done a filter to correct this in the branch [soph-comm](https://github.com/linuxmuster/linuxmuster-webui7/tree/soph-comm), did you try it or have you some others errors with it ?

**Comment by PLanB2008** [comment]
I still have to give it a try. I hope I manage to test it today.
