### ISSUE TITLE
Setup Process

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-webui7#74]
When something goes wrong during the setup the webUI stays in installation mode without possibility to break out.

![grafik](https://user-images.githubusercontent.com/26460239/51324865-0be72a80-1a6c-11e9-8f55-b4585f1a1c15.png)

**Comment by jolly-jump** [comment]
the current documentation says: "restart over with clean appliances" this is the most radical workaround

**Comment by PLanB2008** [comment]
Okay, so this seems to be  sufficient for now, I'll close this issue.
