### ISSUE TITLE
linuxmuster-webui7 (1.0.44-1) upgrade fails

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-webui7#76]
Package upgrade of linuxmuster-webui7 (1.0.44-1) fails:

```
linuxmuster-webui7 (1.0.44-1) wird eingerichtet ...
---------------------------------------------------------------
updating linuxmuster-webui
---------------------------------------------------------------
Stop linuxmuster-webui
Load existing ajenti config file ...
Copy linuxmuster config in /etc/linuxmuster/webui/config.yml ...
Traceback (most recent call last):
  File "/usr/lib/linuxmuster-webui/etc/split_config_aj.py", line 30, in <module>
    config_webui['linuxmuster'] = config_ajenti['linuxmuster']
KeyError: 'linuxmuster'
dpkg: Fehler beim Bearbeiten des Paketes linuxmuster-webui7 (--configure):
 installed linuxmuster-webui7 package post-installation script subprocess returned error exit status 1
```
Previous version was 1.0.41-1.

**Comment by kiarn** [comment]
Hello @HappyBasher ,

Please run ( with right PATH ) : 

`bash /usr/lib/linuxmuster-webui/etc/create_aj_cfg.sh`

and then upgrade.

**Comment by PLanB2008** [comment]
I believe this is a special and rare case.

@HappyBasher did you try to update the linuxmuster-webui package on a host which was prepared (lmn-appliance or whatever) but did not run the lmn-setup?

There were some changes splitting lmn configs from ajenti/config.cfg to webui/config.cfg. This is done by the installation process.

If there is no webui/config.cfg we assume it is an old installation and try to split it from the anenti config. 

EDIT: Today I installed the package from scratch which worked without problems.

**Comment by HappyBasher** [comment]
@kiam
After running the script the package upgrade was successfull. Script output:
```
root@server:~# /usr/lib/linuxmuster-webui/etc/create_aj_cfg.sh
cat: /var/lib/linuxmuster/setup.ini: No such file or directory
cat: /etc/linuxmuster/.secret/global-binduser: No such file or directory
cat: /var/lib/linuxmuster/setup.ini: No such file or directory
cat: /var/lib/linuxmuster/setup.ini: No such file or directory
cat: /var/lib/linuxmuster/setup.ini: No such file or directory
mkdir: cannot create directory ‘/etc/linuxmuster/webui’: File exists
File /etc/linuxmuster/webui/config.yml does not exist.
Bundle certificate for webui
cat: /etc/linuxmuster/ssl/.key.pem: No such file or directory
cat: /etc/linuxmuster/ssl/.cert.pem: No such file or directory
Run Sophomorix-UI to add permissions
```

**Comment by HappyBasher** [comment]
@PLanB2008 
Yes. As recommended I upgraded the appliance before setup when the issue occurs. I think this should be fixed as it unsettles customers.

**Comment by PLanB2008** [comment]
Now I'm confused... 
Either you've a fresh, clean installation - then the package should work as expected , or you have a running installation where ajenti/config.yml contains the linuxmuster settings and you don't have a linuxmuster/config.yml - then postinstall of linuxmuster-webui shoudl trigger the script @kiarn  mentioned.

The only case I see where this fails is if you have a lets say 'old appliance' where linuxmuster-webui is installed but there are no linuxmuster settings because the linuxmuster-setup did not run. This case should be pretty rare, I assume only our testing appliances which can be updated by hand once.

Do I miss something here?

**Comment by kiarn** [comment]
I also think it's only a special case.
I just add a warning about it with a try ... except, and the update should work.
I'm also interested to know in which context this error occurs.

**Comment by zefanja** [comment]
> mkdir: cannot create directory ‘/etc/linuxmuster/webui’: File exists

This will always happens, because the script checks if the directory exists and then tries to create it.

```
if [ -d /etc/linuxmuster/webui ]; then
    mkdir /etc/linuxmuster/webui
fi
```
Just use the `-p` option of `mkdir` and skip the test.

**Comment by kiarn** [comment]
> Just use the `-p` option of `mkdir` and skip the test.

Right !
Thank you, I don't what I was thinking about, it's a dummy error ...
It's done with 3e145ff.
