### ISSUE TITLE
Sophomorix config files

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#77]
Hello,

I've found some old path for sophomorix, and i've corrected them in dfad5b5.
In my installation, i don't have the files /etc/linuxmuster/sophomorix/user/quota* and other config files from sophomorix, but i'm pretty sure it's because i'm testing / deleting in all ways.

I didn't find how to generate these ( not in linuxmuster-setup, linuxmuster-prepare or debian/postinst ).
How should it be created by a fresh install ?

**Comment by jeffbeck** [comment]
The content of quota.txt/mailquota.txt... is saved with sophomorix commands in Active Directory (per user, class,project, ...) or in school. conf for roles

quota.txt
mailquota.txt 

are obsolete in lmn7

**Comment by kiarn** [comment]
@jeffbeck : ok thanks.
The plugin lm_quotas needs some updates then.

**Comment by jeffbeck** [comment]
'hardisk' quota have changed from partition quotas to smb-share(=school) quota.
So there is a change,
For more info see:

https://github.com/linuxmuster/sophomorix4/wiki/Quota

**Comment by kiarn** [comment]
Hello @jeffbeck 

I think I don't get it : the user "de" has a file which weight is 60MB, and with quota, I get : 

    $ quota -wvuls de
    Disk quotas for user LINUXMUSTER\de (uid 10015): 
         Filesystem   space   quota   limit   grace   files   quota   limit   grace
          /dev/sda2  62268K   1605M   2006M               2    822k   1028k    

But with sophomorix-quota, I get : 

```
+------------------------------------------------------------------------------+
| de in default-school                                                         |
+------------------------------------------------------------------------------+
| default-school share for user de in MiB (Mebibyte):                          |
|      2506  (A) default Quota for sophomorixRole 'teacher'                    |
|       ---  (B) No Quota at the users class 'teachers'                        |
|      2506  (C) Quota at the user will override all above settings            |
|            Comment: '---'                                                    |
|      2506  CALC was already set for de on default-school                     |
|            SMB share quota was set to 2627731456 Bytes (2506 MiB)            |
+------------------------------------------------------------------------------+
| linuxmuster-global share for user de in MiB (Mebibyte):                      |
|      2006  (A) default Quota for sophomorixRole 'teacher'                    |
|       ---  (B) No Quota at the users class 'teachers'                        |
|      2006  (C) Quota at the user will override all above settings            |
|            Comment: '---'                                                    |
|      2006  CALC was already set for de on linuxmuster-global                 |
|            SMB share quota was set to 2103443456 Bytes (2006 MiB)            |
+------------------------------------------------------------------------------+
| CloudQuota for user de (100% of default-school share):                       |
|      2506  sophomorixCloudQuotaCalculated was set to 2506 MB                 |
+------------------------------------------------------------------------------+
| MailQuota for user de in MiB (Mebibyte):                                     |
|       306  (A) default MailQuota for sophomorixRole 'teacher'                |
|       ---  (B) No Quota at the users class 'teachers'                        |
|       ---  (C) No MailQuota at the user Object 'de'                          |
|       306  sophomorixMailQuotaCalculated is 306 MiB                          |
+------------------------------------------------------------------------------+
```
With the option "-jj", I get a big JSON with all limits from all users, is it normal ?
What am I doing wrong ?
