### ISSUE TITLE
Strong password

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#78]
Hello,

As I can see, the rules for a strong password are : 

![2019-02-18_09-45](https://user-images.githubusercontent.com/10401079/52938456-011cff80-3362-11e9-81ff-efb9cf221045.png)

Are these rules still ok ? ( I would recommend min 8 chars, but I have to change the regexp for this ).

@jeffbeck : is the list of valid char right ? Can't we put digits ?

**Comment by PLanB2008** [comment]
Hey @kiarn ,
I just missed the digits in the discription.

The valid char regEx is     

    var regExp = /^[a-zA-Z0-9!@#§+\-$%&*{}()\]\[]+$/
, so digits ARE allowed.

**Comment by kiarn** [comment]
Yep thanks, I should have seen this.

I just had password and quota ( not finished ) on the landing page. I think a direct access to change the password is necessary for the majority of the user, but we can remove this if the other dev are not ok with this : 

![2019-02-18_11-57](https://user-images.githubusercontent.com/10401079/52946596-a7720080-3374-11e9-9b9a-45e1bca44cc1.png)

**Comment by PLanB2008** [comment]
I would suggest not to have  the Password change option one the landing page but a button which leads to the existing page, this would keep the landing page cleaner.
In addition changing password is not a every day task so I think having a button which leads to the password change page would be sufficient, what do you think?

**Comment by kiarn** [comment]
> I would suggest not to have the Password change option one the landing page but a button which leads to the existing page, this would keep the landing page cleaner.
> In addition changing password is not a every day task so I think having a button which leads to the password change page would be sufficient, what do you think?

Good suggestion, it's cleaner with only a button, and simple for all user. I can modify this.
