### ISSUE TITLE
quotaangaben ohne Einheit MiB

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#79]
Bei den Quotaangaben feht die Einheit

**Comment by kiarn** [comment]
Hello @jeffbeck 

Do you mean here in schoolsettings ?

![2019-02-25_14-34](https://user-images.githubusercontent.com/10401079/53340965-8ed09000-390a-11e9-9d4e-79ce99175233.png)

**Comment by jeffbeck** [comment]
Yes. (Cloudquota is correct: percent)
If you can grep in your code, and quota appears at other places, change there as well.

Careful: The numbers are in MiB not MB

See:

https://de.wikipedia.org/wiki/Byte#Vergleich

**Comment by kiarn** [comment]
Hello,

I've done it, but the units are hard-encoded. A better way to do this would habe been to convert automatically, but I'll do it later.
