### ISSUE TITLE
Benutzerupdate mit Fehlermeldung

### ISSUE THREAD

**Issue by jeffbeck** [linuxmuster/linuxmuster-webui7#80]
Wenn bei einem Vorhandenen Schüler 
1) die Klasse verändert wird
2) Speicher und Prüfen
3) beim umsetzen kommt der Fehler: sophomorix-move returned error

sophomorix-move gibt es nicht mehr
Der Befehl heisst nun sophonmorix-update

Auf Konsole tut es.

**Comment by kiarn** [comment]
Already fixed.
