### ISSUE TITLE
Question: Students Login

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#83]
Currently it is not possible to login as student. Is this disabled temporarily or should students not log in to the webUI?

**Comment by PLanB2008** [comment]
Currently we do not have plans allowing students to login via WEBUI.

**Comment by zefanja** [comment]
Ok, thanks for the clarification. Do you think there should be a hint or a better error message when a student tries to login? Currently it says "Could not authenticate" or something like this.
