### ISSUE TITLE
Mixed translations workflow

### ISSUE THREAD

**Issue by kiarn** [linuxmuster/linuxmuster-webui7#84]
https://github.com/linuxmuster/linuxmuster-webui7/blob/f1280c3ce065299195227ba067fbd78f611a98fa/usr/lib/linuxmuster-webui/plugins/lmn_session/resources/partial/session.html#L52

@PLanB2008 : this line mix the translation filter and the use of the angular-translate module.
What should we use in priority in this case ?

I would suggest angular-translate.

**Comment by PLanB2008** [comment]
You're right. I agree with your suggestion. I'm gonna update it in a minute.
