### ISSUE TITLE
LINBO-Group Default TFTP set to "10.16.1.1" despite different server address

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-webui7#86]
When creating a new LINBO group the default value for TFTP Server is set to "10.16.1.1", despite the server having the address "10.0.0.1". It was selected "start.conf.win10" on the Create-Button

**Comment by kiarn** [comment]
Related to https://github.com/linuxmuster/linuxmuster-base7.

**Comment by PLanB2008** [comment]
created issue in linuxmuster-base
https://github.com/linuxmuster/linuxmuster-base7/issues/69

**Comment by kiarn** [comment]
> created issue in linuxmuster-base
> [linuxmuster/linuxmuster-base7#69](https://github.com/linuxmuster/linuxmuster-base7/issues/69)

Duplicate from https://github.com/linuxmuster/linuxmuster-base7/issues/66 and resolved today from @HappyBasher.
