### ISSUE TITLE
Name of school during setup not reflected in School name (Print data)

### ISSUE THREAD

**Issue by RolandBBerlin** [linuxmuster/linuxmuster-webui7#87]
During Setup a name for the school was entered. However, when opening administrative webui at school data the name "Default School" is shown and must be changed then.

**Comment by PLanB2008** [comment]
Well these are different values. The one provided during the setup process is used to create the certificate. So this is kind of a global name. The name configured in the settings dialogue represents the value  of the  SCHOOL_LONGNAME attribute in default-school/school.conf
On the other hand, from a user perspective I agree with you. 

@jeffbeck @HappyBasher 

What do you think? I suppose we agree that the SCHOOL_LONGNAME should be set by default the same as the one set in setup wizard / lmn-prepare.   Where should we implement this?

**Comment by PLanB2008** [comment]
I reacteted this ticket in lmn-base
https://github.com/linuxmuster/linuxmuster-base7/issues/82
