### ISSUE TITLE
Cups printers

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-webui7#94]
Cups printers do not show up in the admin device management.

To reproduce create a cups pdf printer with the cups web interface.

**Comment by HappyBasher** [comment]
Hi kiarn!
Maybe it was not so a good idea to get the printers from printers.conf because we need an ad group anyway. I'd like to know what the others think. However, printer entries in devices.csv cannot cover the cases where a printer has multiple queues on the cups server.
Regards, ts

**Comment by kiarn** [comment]
Hi @HappyBasher 

> Maybe it was not so a good idea to get the printers from printers.conf because we need an ad group anyway.

Yes, I'm aware of it, that's why I asked for a complete method on discourse.
It's only a temporary fix to only show up the printers, it's not a problem to fix this later.
