### ISSUE TITLE
Teacher cannot assign project users

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-webui7#95]
There is no possibility for a teacher to assign project users in the webui.

**Comment by kiarn** [comment]
Hello @HappyBasher 

For a teacher, it is possible under Groupmembership --> clic on group --> edit member : 

![project1](https://user-images.githubusercontent.com/10401079/55878296-6f30b680-5b9c-11e9-87ec-12e6fab71fbf.png)

and then 

![project2](https://user-images.githubusercontent.com/10401079/55877890-7dca9e00-5b9b-11e9-8105-a5f32af6e6e9.png)

But, I think there's still some fix to do : 

1. global-admin have no access to groupmembership : is there a reason why ?
2. teacher can only add a student in a project. I think it would be good to let a teacher add another teacher in a project,
3. We can directly add a link to edit a group on the main page for an user-friendly experience, and not show the DN.

**Comment by kiarn** [comment]
Global-admin can yet add teachers in a group. 
I think it would be good to let teachers add teachers into a project, but they need the authorization "ln:users:teachers:read", or we need to split this authorization.
@HappyBasher and @PLanB2008 : are you ok with this or any suggestion ?

**Comment by PLanB2008** [comment]
Well it depends. I think we've to take a look in the permission structure.

There are kind of sensitive information a teacher should not be able to see. Eg. birthday, group memberships of other teachers and the initial password. 

The cleanest way would be to split the authorization.

**Comment by kiarn** [comment]
In the initial way of coding, we need the information group membership to get the user from a specific project. So I added the authorization `lm:users:teachers:list` for the action `get-all`, available for all teachers, and let `lm:users:teachers:read` for the rest.

With `get-all`, a teacher can also access the quota ...

So, it's not perfect. Another way would be to get the list from teachers ( first name + last name ) from the CSV, and compare this to the output from `sophomorix-project -i -p PROJECT` to complete the checkbox.
Or is there a simplier way to get the teachers member from a specific group with sophomorix ?

**Comment by PLanB2008** [comment]
Well I don't think this is a big issue.
