### ISSUE TITLE
Redirect to landing page if user lacks permission

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#97]
When I want to login as a teacher I get this error (trying to access the landing page):

```Security Error: Permission "lm:users:teachers:read" is required```

The landing page does not load because of that.

**Comment by zefanja** [comment]
Looks like ajenti saves the last accessed site. So if I was logged in with `global-admin` before and edited some students / teachers (e.g. /view/lm/users/teachers) and then log out and log in again as a teacher it will redirect to that page and result in the error above.

**Comment by kiarn** [comment]
Hello @zefanja,

> Looks like ajenti saves the last accessed site.

That's right. I will see if it's possible to redirect to the landing page after login if the user have no permission for the saved path.

**Comment by PLanB2008** [comment]
@kiarn how about redirect to the root on logout / autologout (expired session)

so redirecting on logout from https://server:8000/view/lm/users/schooladmins to https://server:8000

**Comment by kiarn** [comment]
@PLanB2008 : good idea.
I read the code from ajenti to redirect to root if user has not sufficient permission, but it's not so easy.

**Comment by kiarn** [comment]
Pull request done here : https://github.com/ajenti/ajenti/pull/1173
