### ISSUE TITLE
After setup redirection to HTTPS does not work

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-webui7#99]
With the lastest version of the webUI it does not redirect to HTTPS. When I click on the "Close" button it says "Restart(ed) WebUI", but it does not redirect.

Is there a timeout and how long is it? I waited maybe 1 minute. I could access the website with https just fine, but manually.

**Comment by kiarn** [comment]
Hello @zefanja,

> With the lastest version of the webUI

Do you mean git or package ?
I think I already solved this with https://github.com/linuxmuster/linuxmuster-webui7/commit/fdd3a0c5d92409577822f7f5bdb14aaedeb80cad

**Comment by zefanja** [comment]
The package from the repo. I'll try again with the git version.

**Comment by kiarn** [comment]
Any news on it ?

**Comment by PLanB2008** [comment]
I updated the repo package last friday so there should be an improvement (if the fix works).

**Comment by PLanB2008** [comment]
This is confirmed to work now.
